Add @javisorribes as a reviewer for ES
google/comprehensive-rust pull request #1090
Opened 2023-08-18 09:58 UTC by JaviSorribes

2023-08-18 12:31 UTC, djmitche requested changes

2023-08-18 12:31 UTC, djmitche commented on .github/CODEOWNERS
> +po/es.po @deavid @javisorribes
```suggestion
po/es.po @deavid @JaviSorribes
```

2023-08-18 12:59 UTC, djmitche approved these changes
Hm, GitHub is still saying it's invalid, perhaps because you don't have write access to the repo. @mgeisler may need to fix that :)

2023-08-18 20:24 UTC, henrif75 commented
> Hm, GitHub is still saying it's invalid, perhaps because you don't have write access to the repo. @mgeisler may need to fix that :)

I gave @JaviSorribes write permission.

2023-08-18 20:26 UTC, henrif75 commented
@JaviSorribes please accept the invite from GitHub. You'll also need to accept the Google CLA at https://cla.developers.google.com/cla

2023-08-24 10:31 UTC, mgeisler commented
> You'll also need to accept the Google CLA at https://cla.developers.google.com/cla

Small note: this is not necessary for Googlers — I guess the page will say the same :smile:

2023-08-24 21:24 UTC, henrif75 commented
> > You'll also need to accept the Google CLA at https://cla.developers.google.com/cla
> 
> Small note: this is not necessary for Googlers — I guess the page will say the same 😄

Got it, should the test be changed to account for it?

2023-08-24 21:24 UTC, merged

2023-08-25 06:26 UTC, mgeisler commented
> Got it, should the test be changed to account for it?

It should already be green when people use their `@google.com` email address in the commits. There has been a few cases where people accidentally used their private addresses and we had to fix this by rewriting the commits. We don't have much control over this check — it's added via a global setting on the `google` GitHub organization.

2023-09-09 17:11 UTC, JaviSorribes commented
Hi, sorry but I didn't have notifications configured (fixed) and the invitation is now expired. Could you please send again?