Add `typos` to CI
google/comprehensive-rust pull request #1158
Opened 2023-09-01 17:48 UTC by antoniolinhart

Hi all!

This CL:
* Avoids including current false-positives in the checking of typos
* Excludes localization-related files as `typos` works with English words
* Fixes existing typos caught in the repo

.. yet to verify this in CI since I am not yet familiar with GH Actions

2023-09-01 18:56 UTC, antoniolinhart commented
Sorry for all of the workflow runs - was trying to see whether this worked or not. Do I need to be worried about the number of commits or does it automatically get squashed upon merging?

Thanks!!

2023-09-04 08:10 UTC, mgeisler commented on _typos.toml
Is it possible to "hide" this file inside the `.github/workflows/` directory? That way it doesn't take away space for everybody who browses https://github.com/google/comprehensive-rust/.

2023-09-04 08:15 UTC, mgeisler commented
> Sorry for all of the workflow runs - was trying to see whether this worked or not.

No worries about those — I didn't get emailed about them so it was probably only spamming yourself :smile: 

> Do I need to be worried about the number of commits or does it automatically get squashed upon merging?

Because we've gotten a lot of drive-by commits, I've disabled the normal merges on this repository. We only use squash commits and the commit message defaults to the PR title and description. This makes the history much cleaner and it lowers the bar for entry for people who are not comfortable rebasing and squashing commits themselves.

So don't worry about it, just make sure the PR has a useful title and description.

2023-09-04 08:16 UTC, mgeisler requested changes
Thanks so much for this, it looks great! In particular, it's great that you fixed the existing typos in this PR as well.

I would love if you could move the config file inside the `.github/` directory — possibly next to the `labeler.yml` config file.

2023-09-05 17:28 UTC, antoniolinhart commented on _typos.toml
Yup! Moved the file and confirmed it still works properly

2023-09-05 17:36 UTC, antoniolinhart commented
Moved the typos file and confirmed (by adding a typo) that the config file still works :+1:

2023-09-05 20:18 UTC, mgeisler approved these changes
Thanks, I look forward to a typo-free future :smile:

2023-09-05 20:20 UTC, antoniolinhart commented
> Thanks, I look forward to a typo-free future 😄

Oh thanks for the fix!! I mistakenly moved it to the wrong dir

2023-09-05 20:21 UTC, mgeisler commented
> > Thanks, I look forward to a typo-free future 😄
> 
> Oh thanks for the fix!! I mistakenly moved it to the wrong dir

All good, your testing made it easy for me to move it!

2023-09-05 20:21 UTC, merged