es: Translations - Day 1 afternoon
google/comprehensive-rust pull request #1167
Opened 2023-09-05 17:27 UTC by henrif75

Part of #284

2023-09-05 20:29 UTC, deavid requested changes

2023-09-05 20:29 UTC, deavid commented on po/es.po
> +"La comprobación de límites no se puede inhabilitar con una bandera de "
At least to me 'inhabilitar' has a different meaning (https://www.fundeu.es/consulta/inhabilitar-y-deshabilitar-609/). 'deshabilitar' has widespread use, or 'desactivar' might be also a good replacement

2023-09-05 20:29 UTC, deavid commented on po/es.po
> +msgstr "No hay sobrecarga de FFI"
'sobrecarga' is 'overload', not overhead. No overhead FFI means no added performance penalty when calling FFI.

2023-09-05 20:29 UTC, deavid commented on po/es.po
> +msgstr "Grandes errores del compilador."
"Great compiler errors." here means that the compiler errors are really good and nice, not that they are big.

2023-09-05 20:29 UTC, deavid commented on po/es.po
> +"tienes que 'pagar' por construcciones de programación de nivel superior con "
programación de alto nivel

2023-09-05 20:29 UTC, deavid commented on po/es.po
> +msgstr "Números de punto flotante"
"Números de coma flotante" - https://es.wikipedia.org/wiki/Coma_flotante

2023-09-05 20:29 UTC, deavid commented on po/es.po
> +msgstr ""
can you provide a translation fix instead of removing it?

2023-09-05 20:29 UTC, deavid commented on po/es.po
> +"En la función principal, la instrucción de impresión solicita la "
"main" is the proper noun and name of the main() function, better leave it untranslated.

2023-09-05 20:29 UTC, deavid commented on po/es.po
> +"valores durante su  tiempo de vida."
double space in " su  "

2023-09-05 20:31 UTC, deavid commented
Overall I see this PR as a huge improvement to the Spanish translation. However I'm not very keen on translating every programming specific term into English, and we should be a bit more careful on making this suitable too for Spanish speakers outside of Spain.

2023-09-06 17:50 UTC, henrif75 commented on po/es.po
> +msgstr "Rust se asemeja bastante a C++:"
Thanks, all this translation came from the localization services team. Can you suggest a better translation (I'm not fluent in Spanish :) )

2023-09-06 18:33 UTC, henrif75 commented on po/es.po
> +msgstr "No tiene tiempos de ejecución ni recolección de memoria residual."
Do you suggest keeping these terms in English italicized?

2023-09-06 19:33 UTC, deavid commented on po/es.po
> +msgstr "No tiene tiempos de ejecución ni recolección de memoria residual."
yes, italicized is the recommendation from RAE for dealing with foreign words. I recommend doing that instead.

2023-09-06 19:35 UTC, deavid commented on po/es.po
> +msgstr "Rust se asemeja bastante a C++:"
"Rust satisface las mismas necesidades que C++:" might be a better wording although it sounds different than english, it seems to convey the same thing.

2023-09-06 20:03 UTC, henrif75 commented on po/es.po
> +"desbordamiento de enteros con tiempo de ejecución."
I also restored the term "runtime".

2023-09-06 20:34 UTC, henrif75 commented on po/es.po
> +"semántica envolvente. De forma predeterminada, se obtienen pánicos en el "
I restored the wrap-around term.

2023-09-06 20:43 UTC, henrif75 commented
Thanks so much @deavid for your thorough review. I've made all your suggested changes, PTAL.

2023-09-06 20:53 UTC, deavid commented
I reviewed two more in the meantime. I'll be OOO for the next 2 weeks. I'll try to push some reviews before going OOO, but on next monday you might need to reach out to a different reviewer to get unblocked.

2023-09-06 20:56 UTC, deavid approved these changes

2023-09-06 20:57 UTC, henrif75 commented
> I reviewed two more in the meantime. I'll be OOO for the next 2 weeks. I'll try to push some reviews before going OOO, but on next monday you might need to reach out to a different reviewer to get unblocked.

Thanks again!

2023-09-06 21:10 UTC, merged