Add solution for Health Statistics exercise
google/comprehensive-rust pull request #1172
Opened 2023-09-06 03:28 UTC by fw-immunant

2023-09-07 08:35 UTC, mgeisler requested changes
Thanks for cleaning up the order of the exercises in the SUMMARY... we forgot that when we closed #1135.

We should just make sure that the solution is incorporated correctly in the rest of the course.

2023-09-07 08:35 UTC, mgeisler commented on src/exercises/day-2/health-statistics.rs
This doesn't follow the system (eh, more like "guidelines") of the other solutions. That is, I normally tried to reuse the same Rust file for both the exercise and the solution. For the exercise, I would include only part of the file — the solution is then the full file.

It's tedious, but it ensures some level of consistency between the function signatures in the exercise and the solution.

The solution is the then also added to the `src/exercises/Cargo.toml` file to ensure it gets built by `cargo check` in CI.

2023-09-26 06:13 UTC, fw-immunant commented on src/exercises/day-2/health-statistics.rs
I think I've gotten this aligned with how the other solutions are done.

2023-09-26 07:27 UTC, mgeisler approved these changes
Thanks, it aligned! I realize now how messy this system is... :grimacing:

2023-09-26 07:28 UTC, mgeisler commented on src/exercises/day-2/health-statistics.rs
You did! It looks a bit ugly, but that's not your fault :smile:

It would be interesting if we could use a better template engine here as well (like in https://github.com/google/mdbook-i18n-helpers/issues/70).

2023-09-26 07:29 UTC, merged