fr: removing references to Rust (as in... "iron oxide", "rouille" in French)
google/comprehensive-rust pull request #1214
Opened 2023-09-16 17:23 UTC by yohcop

Plus a few more things I saw on the way.

Related to French translation #323

2023-09-16 19:48 UTC, sakex commented on po/fr.po
> -msgstr "Binaires de rouille"
Excellent

2023-09-16 19:57 UTC, sakex requested changes

2023-09-16 19:57 UTC, sakex commented on po/fr.po
> +msgstr "Terminologie de la Rust :"
```suggestion
msgstr "Terminologie de Rust :"
```

2023-09-16 19:57 UTC, sakex commented on po/fr.po
> +"Python, et Go. Rust n'est pas distribue avec plusieures choses que vous "
```suggestion
"Python, et Go. Rust n'est pas distribué avec certains éléments que vous "
```

2023-09-16 19:57 UTC, sakex commented on po/fr.po
> +"Les énumérations de Rust sont emballés étroitement, en tenant compte des "
```suggestion
"Les énumérations de Rust sont emballées étroitement, en tenant compte des "
```

2023-09-16 19:57 UTC, sakex commented on po/fr.po
> +"Voir [Filtrage par motif](../pattern-matching.md) pour plus de détails sur les "
Est-ce que ce lien marche vraiment?

2023-09-16 19:57 UTC, sakex commented on po/fr.po
> +"aujourd'hui. Alors essayez de trouvez un petit coin de votre code où "
```suggestion
"aujourd'hui. Alors essayez de trouver un petit coin de votre code où "
```

2023-09-16 19:57 UTC, sakex commented on po/fr.po
> +"analyse quelques octets bruts serait idéal."
```suggestion
"analyse quelques octets de donnée brute serait idéal."
```

2023-09-16 19:59 UTC, sakex commented
Merci pour la review, les erreurs sont assez cocasses

2023-09-17 09:14 UTC, yohcop commented on po/fr.po
> +"Voir [Filtrage par motif](../pattern-matching.md) pour plus de détails sur les "
Oui, ca marche. Ce message est utilise dans src/control-flow/....md, donc ../pattern-matching.md est toujours valide.
C'est un peu un coup de chance ceci dit...

2023-09-17 14:21 UTC, sakex approved these changes

2023-09-17 16:03 UTC, yohcop commented
Thanks for the review!

It looks like the ...@senges.ch email is missing the google cla (https://github.com/google/comprehensive-rust/pull/1214/checks?check_run_id=16863101887). I'm sure you did it with a different email already though.... :)

2023-09-17 19:25 UTC, sakex approved these changes

2023-09-17 19:29 UTC, merged

2023-09-17 19:29 UTC, sakex commented
I wasn't aware of this. Thanks 😁