fa: Translate Part `3` , `4` , `5` ,`6.1`, `6.2`, `6.3`
google/comprehensive-rust pull request #1439
Opened 2023-10-31 12:48 UTC by moaminsharifi

Part of #671
Summary of changes:

- Translate Part `3` , `4` , `5` ,`6.1`, `6.2`, `6.3`
*for making easier for Reviewers, I just translate until `#: src/basic-syntax/references.md:3`*

I manage to handle all of ltr textes between in rtl texts which have bidi issue:

for example:
- `++C` instead of `C++`
- `!println` instead of `println!`
![2023-10-31 16_05_45-سلام دنیا - Comprehensive Rust 🦀](https://github.com/google/comprehensive-rust/assets/11869014/f91b7d65-f850-4266-b4aa-fa0d0a05cd97)
Or:

![2023-10-31 15_11_38-تایپ‌های عددی - Comprehensive Rust 🦀](https://github.com/google/comprehensive-rust/assets/11869014/e0e26156-cab0-4dcc-91fa-1be7550f9b82)
which is so messy in the table, and now is:
![2023-10-31 16_14_07-تایپ‌های عددی - Comprehensive Rust 🦀](https://github.com/google/comprehensive-rust/assets/11869014/b700f4f5-af5e-48ce-86fa-5dddd3d07c48)

Thanks to @mgeisler for checking and merging pull request #1433, the changes have greatly improved BiDi in the project.

2023-10-31 14:20 UTC, prmadev reviewed
Could not go further than line 2426 at the moment. But for now, here are some of my comments.

2023-10-31 15:56 UTC, moaminsharifi commented on po/fa.po
> +msgstr "می‌تواند به دستگاه‌های بسیار محدود مانند میکروکنترلرها مقیاس‌بندی شود."
Because most of the time, we mention first time one text and then use a new style, I think it's fine.

2023-10-31 16:00 UTC, moaminsharifi commented on po/fa.po
> +"رشته‌های Rust با انکودینگ UTF-8 هستند و می‌توانند شامل هر کاراکتر Unicode "
Sometimes I go to various dictionaries and check parts of speech but still hard to make it understandable with the originality of the main text.

2023-10-31 16:21 UTC, DannyRavi commented on po/fa.po
> +"تا رویکرد‌های Rust را بهتر توضیح دهیم یا در در حالت مقایسه با آن قرار دهیم."
redundant در

2023-10-31 18:08 UTC, moaminsharifi commented on po/fa.po
> +"    let mut x: i32 = 6;  //انتساب متغییر قابل تغییر\n"
In the original text, it says "*Mutable variable binding*". It is not a direct use of "*definition*" which we can say "تعریف کردن" is a good meaning for it.
So I take it as "انتساب".

2023-10-31 18:39 UTC, hamidrezakp commented on po/fa.po
> +"    let mut x: i32 = 6;  //انتساب متغییر قابل تغییر\n"
I agree with using "انتساب" for binding cause it's different than "تعریف کردن" which is define.

2023-10-31 19:07 UTC, DannyRavi approved these changes

2023-10-31 19:07 UTC, DannyRavi commented on po/fa.po
> +msgstr "مقادیر حافظه انواع به شرح زیر است:"
This sentence is a little unclear.

2023-10-31 19:09 UTC, DannyRavi commented
Thanks to @moaminsharifi  for translating some of the texts.

2023-10-31 19:41 UTC, moaminsharifi commented on po/fa.po
> +"حتما از کلاس بپرسید که با چه زبان‌هایی تجربه دارند. بسته به پاسخ، می توانید "
Because it's is in the context of "Speaker Notes", Object of sentence is "Teacher" and Subject "class" so I take "کلاس" for i.

2023-10-31 19:46 UTC, moaminsharifi commented on po/fa.po
> +msgstr "مقادیر حافظه انواع به شرح زیر است:"
what about "مقادیر اشغال شده توسط حافظه انواع مختلف به شرح زیر است:"

2023-10-31 19:51 UTC, moaminsharifi commented on po/fa.po
> +msgstr "هیچ موتکس قفل شده فراموش شده وجود ندارد."
It's hard to say no to owner of repo, I checked whole file and there only one time mention to "*forgotten locked mutexes*" and it's one word so I translated it to single word.

2023-10-31 19:55 UTC, moaminsharifi commented on po/fa.po
> +msgstr "انتزاع‌هایی با هزینه صفر"
It's really challenging to translate "low-cost" into "zero-cost".

Additionally, following this text, there is more to mention about how Rust compiles any abstraction to its simplest possible form

2023-10-31 21:12 UTC, hamidrezakp commented on po/fa.po
> +msgstr "هیچ موتکس قفل شده فراموش شده وجود ندارد."
What about this?
```suggestion
msgstr "هیچ موتکس قفل شدهِ فراموش شده‌ای وجود ندارد."
```

2023-10-31 21:13 UTC, hamidrezakp commented on po/fa.po
> +msgstr "هیچ موتکس قفل شده فراموش شده وجود ندارد."
> It's hard to say no to owner of repo

We are all owners of this file 😄, so don't be shy, argue anything you think may be better.

2023-10-31 21:15 UTC, hamidrezakp commented on po/fa.po
> +msgstr "انتزاع‌هایی با هزینه صفر"
What about this?
```suggestion
msgstr "انتزاع‌هایی بدون هزینه"
```

2023-10-31 21:17 UTC, hamidrezakp commented on po/fa.po
> +msgstr "مقادیر حافظه انواع به شرح زیر است:"
The context is for how many bytes the types occupy in memory, and we can translate the sentence as this:
"‍اندازه تایپ‌ها به شرح زیر است:"

2023-10-31 21:20 UTC, hamidrezakp commented on po/fa.po
> +msgstr "بر قابلیت اطمینان و ایمنی بدون قربانی کردن عملکرد تمرکز دارد."
I even suggest to use "پرفورمنس", i know it's bad, but the word have no better alternative in Persian that i am aware of.

2023-10-31 22:16 UTC, mgeisler commented on po/fa.po
> +msgstr "هیچ موتکس قفل شده فراموش شده وجود ندارد."
Oh, and if you find English sentences which you cannot translate because they don't sense in isolation, then we should fix this in the original sentence.

A problem that I ran into is "Non-Goals" on the [very first page](https://google.github.io/comprehensive-rust/#non-goals): we don't really speak like that in Danish and I don't know how to translate it in a faithful way. Right now, the Danish translation is "Things that are not covered" and I should really submit this as a fix to the English text.

2023-10-31 22:27 UTC, hamidrezakp commented on po/fa.po
> +msgstr "هیچ موتکس قفل شده فراموش شده وجود ندارد."
Good point, and other than this, we have few technical words in Persian and the lack of vocabulary will get us to the point that we have to use the exact word in but in Persian letters and it's awful.

But it would be very helpful if we can make the original text simpler in to avoid this situations.

2023-11-03 07:57 UTC, hamidrezakp requested changes
Sorry for the size of comments, a lot of them are ZWNJ's.

Thank you again, great work.

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +"زبان Rust دارای ماکروهای ترتمیز است، <span dir=ltr>`println!`</span> یک "
Hygienic in here means that Rust macros can not use variables in the scope they are called, So translating it to "ترتمیز" will lose a lot of meaning in here. let's just stick to the original word and later we may find a better phrasing for this meaning.
```suggestion
"زبان Rust دارای ماکروهای hygienic است، <span dir=ltr>`println!`</span> یک "
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +"رشته‌های Rust با انکودینگ UTF-8 هستند و می‌توانند شامل هر کاراکتر Unicode "
```suggestion
"رشته‌های Rust دارای انکودینگ UTF-8 هستند و می‌توانند شامل هر کاراکتر یونیکد "
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +"span>/Java است.یک زبان امری است (imperative) و سعی نمی کند چیزی را مگر اینکه "
```suggestion
"span>/Java است.یک زبان امری است (imperative) و سعی نمی‌کند چیزی را مگر اینکه "
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +msgstr "زبان Rust, یک زبان مدرن با پشتیبانی کامل از چیزهایی مانند Unicode است."
```suggestion
msgstr "زبان Rust, یک زبان مدرن با پشتیبانی کامل از چیزهایی مانند یونیکد است."
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +"شناسه‌ها را از اسکوپ‌ای که در آن استفاده می‌شوند، ضبط نمی‌کنند.ماکروهای Rust در "
```suggestion
"شناسه‌ها را از اسکوپ‌ای که در آن استفاده می‌شوند، ضبط نمی‌کنند. ماکروهای Rust در "
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +"[برنامه نویسی شی گرا](https://doc.rust-lang.org/book/ch17-00-oop.html) است و "
```suggestion
"[برنامه نویسی شی‌گرا](https://doc.rust-lang.org/book/ch17-00-oop.html) است و "
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +"در حالی که یک زبان تابعی(`functional‍`) نیست، شامل طیف وسیعی از [مفاهیم تابعی]"
```suggestion
"در حالی که یک زبان فانکشنال(`functional‍`) نیست، شامل طیف وسیعی از [مفاهیم فانکشنال]"
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +"    print!(\"{x}\");       // ماکرویی برای پرینت به مانند printf\n"
```suggestion
"    print!(\"{x}\");       // ماکرویی برای چاپ‌کردن به مانند printf\n"
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +"    while x != 1 {       // هیچ پرانتزی دور دستور نیست\n"
```suggestion
"    while x != 1 {       // هیچ پرانتزی اطراف دستور نیست\n"
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +"        if x % 2 == 0 {  // دستور Math به مانند بقیه زبان ها \n"
```suggestion
"        if x % 2 == 0 {  // محاسبات مانند بقیه زبان ها \n"
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +"نشان دهید که چگونه در صورت تمایل به چاپ عبارتی که پیچیده تر از یک متغیر واحد "
```suggestion
"نشان دهید که چگونه در صورت تمایل به چاپ عبارتی که پیچیده‌تر از یک متغیر واحد "
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +"`std::fmt` را که قوانین زبان-کوچک قالب بندی  را دارد جستجو کنند. مهم است که "
```suggestion
"`std::fmt` را که قوانین زبان-کوچک قالب‌بندی را دارد جستجو کنند. مهم است که "
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +"‍`std::fmt` را توی مرورگری کند."
```suggestion
"‍`std::fmt` را توی مرورگر باز کند."
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +"وام گیری (اشاره به مبحث قرض گرفتن یا  `borrow`) ، یک سری کامل از _خطاهای "
```suggestion
"قرض‌گیری (اشاره به مبحث قرض گرفتن یا  `borrow`) ، یک سری کامل از _خطاهای "
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +"زمان اجرا_ را از بین می برد.t  عملکردی مانند C و <span dir=ltr>C++</span> را "
```suggestion
"زمان اجرا_ را از بین می‌برد .t  عملکردی مانند C و <span dir=ltr>C++</span> را "
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +"دارید اما مشکلات عدم ایمنی حافظه را ندارید. علاوه بر این، شما  یک زبان مدرن "
```suggestion
"دارید اما مشکلات عدم ایمنی حافظه را ندارید. علاوه بر این، شما یک زبان مدرن "
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +"با ساختارهایی مانند تطابق الگو و مدیریت وابستگی داخلی دریافت می کنید."
```suggestion
"با ساختارهایی مانند تطابق الگو و مدیریت وابستگی داخلی دریافت می‌کنید."
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +"زبان‌ها  دریافت می‌کنید، به علاوه یک احساس زبان سطح بالا مشابه. علاوه بر این، "
```suggestion
"زبان‌ها دریافت می‌کنید، به علاوه یک احساس زبان سطح بالا مشابه. علاوه بر این، "
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +"شما عملکرد  سریع و قابل پیش‌بینی مانند C و <span dir=ltr>C++</span> (بدون "
```suggestion
"شما عملکرد سریع و قابل پیش‌بینی مانند C و <span dir=ltr>C++</span> (بدون "
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +"راست ایمن تمام این باگ‌ها را غیرممکن می کند:"
```suggestion
"راست ایمن تمام این باگ‌ها را غیرممکن می‌کند:"
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +"_چطوری زبان راست در اینجا بهتر عمل میکند?_  \n"
```suggestion
"_چطوری زبان راست در اینجا بهتر عمل می‌کند?_  \n"
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +msgstr "منابع در پایان دامنه از طریق ویژگی `Drop` آزاد می‌شوند."
```suggestion
msgstr "منابع در پایان اسکوپ از طریق ویژگی `Drop` آزاد می‌شوند."
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +"برش‌های بافر اندازه خود را حمل می کنند و به خاتمه دهنده `NUL` متکی نیستند."
```suggestion
"برش‌های بافر اندازه خود را حمل می‌کنند و به خاتمه دهنده `NUL` متکی نیستند."
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +"حافظه اختصاص داده شده به پشته از طریق ویژگی `Drop` زمانی آزاد می شود که "
```suggestion
"حافظه اختصاص داده شده به پشته از طریق ویژگی `Drop` زمانی آزاد می‌شود که "
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +"`Box` موردنظر اسکوپ مربوطه را ترک کند.‍"
```suggestion
"`Box` مورد نظر اسکوپ مربوطه را ترک کند.‍"
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +"دسترسی‌های خارج از محدوده باعث پانیک می شوند یا می توان آنها را از طریق متد "
```suggestion
"دسترسی‌های خارج از محدوده باعث پانیک می‌شوند یا می‌توان آنها را از طریق متد "
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +"get یک  برش (`slice`) بررسی کرد."
```suggestion
"get یک برش (`slice`) بررسی کرد."
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +msgstr "دستور `match` الزام می کند که حالات بررسی شوند."
```suggestion
msgstr "دستور `match` الزام می‌کند که حالات بررسی شوند."
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +"توابع خطار پذیر در زبان Rust مقدار Result را برمی‌گردانند  که باید باز شوند و "
```suggestion
"توابع خطا پذیر در زبان Rust مقدار Result را برمی‌گردانند که باید باز شوند و "
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +"کامپایلر هشدار می دهد."
```suggestion
"کامپایلر هشدار می‌دهد."
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +msgstr "مدیریت حافظه استاتیک در زمان کامپایل:"
```suggestion
msgstr "مدیریت حافظه ایستا در زمان کامپایل:"
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +msgstr "هیچ متغیر غیر ساخته شده (`uninitialized`) وجود ندارد."
```suggestion
msgstr "هیچ متغیر مقدار‌دهی نشده‌ای (`uninitialized`) وجود ندارد."
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +msgstr "هیچ اشاره گر `NULL` وجود ندارد."
```suggestion
msgstr "هیچ اشاره‌گر `NULL` وجود ندارد."
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +msgstr "عدم اعتبار تکرارکننده."
```suggestion
msgstr "تکرارکننده‌ها (`iterators`) هیچگاه نامعتبر نمی‌شوند.."
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +"struct.Box.html#method.leak)</span>  برای نشت دادن یک اشاره گر استفاده کنید."
```suggestion
"struct.Box.html#method.leak)</span>  برای نشت دادن یک اشاره‌گر استفاده کنید."
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +"یک مورد استفاده از این کار می تواند برای بدست آوردن متغیرهای ایستا با "
```suggestion
"یک مورد استفاده از این کار می‌تواند برای بدست آوردن متغیرهای ایستا با "
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +"کند (به این معنا که مخرب هرگز اجرا نمی شود)."
```suggestion
"کند (به این معنا که تابع مخرب (`destructor`) هرگز اجرا نمی‌شود)."
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +"همچنین می توانید به طور تصادفی یک [چرخه ارجاع](https://doc.rust-lang.org/"
```suggestion
"همچنین می‌توانید به طور تصادفی یک [چرخه ارجاع](https://doc.rust-lang.org/"
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +"نظر می گیرند و Rust از آن محافظت نمی کند."
```suggestion
"نظر می‌گیرند و Rust از آن محافظت نمی‌کند."
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +"برای این دوره، «هیچ نشت حافظه ای» باید به عنوان «هیچ نشت حافظه تصادفی» "
```suggestion
"برای این دوره، «هیچ نشت حافظه ای» باید به عنوان «تقریبا هیچ نشت حافظه _تصادفی_» "
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +"درنظر  گرفته شود."
```suggestion
"درنظر گرفته شود."
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +msgstr "هیچ رفتار تعریف نشده ای در زمان اجرا:"
```suggestion
msgstr "هیچ رفتار تعریف نشده‌ای در زمان اجرا:"
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +msgstr "دسترسی به آرایه محدوده بررسی می شود."
```suggestion
msgstr "دسترسی به آرایه با بررسی محدوده چک می‌شود."
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +"بررسی محدوده نمی تواند با پرچم کامپایل غیرفعال شود. همچنین نمی توان آن را به "
```suggestion
"بررسی محدوده نمی‌تواند با پرچم کامپایل غیرفعال شود. همچنین نمی‌توان آن را به "
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +"امکان می دهد توابعی مانند `slice::get_unchecked` را صدا بزنید که بررسی "
```suggestion
"امکان می‌دهد توابعی مانند `slice::get_unchecked` را صدا بزنید که بررسی "
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +"محدوده را انجام نمی دهد. "
```suggestion
"محدوده را انجام نمی‌دهد. "
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +msgstr "پشتیبانی عالی از پروتکل‌های سرور."
```suggestion
msgstr "پشتیبانی عالی از LSP‌."
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +"انتزاع‌هایی با هزینه صفر، مشابه <span dir=ltr>C++</span>، به این معنی است که "
```suggestion
"انتزاع‌های بدون هزینه، مشابه <span dir=ltr>C++</span>، به این معنی است که "
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +"شما مجبور نیستید برای  ساختارهای برنامه نویسی سطح بالاتر با حافظه یا CPU "
```suggestion
"شما مجبور نیستید برای  ساختارهای برنامه‌نویسی سطح بالاتر با حافظه یا CPU "
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +"«هزینه» ای پرداخت کنید. به عنوان مثال، نوشتن یک حلقه با استفاده از for باید "
```suggestion
"«هزینه»‌ای پرداخت کنید. به عنوان مثال، نوشتن یک حلقه با استفاده از for باید "
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +"ارزش ذکر را دارد که شمارشگرهای زبان Rust  از «انواع داده جبری» هستند که "
```suggestion
"ارزش ذکر را دارد که Enum‌های زبان Rust  از «انواع داده جبری» هستند که "
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +"همچنین به  عنوان «انواع جمع» شناخته می شوند، که به سیستم نوع اجازه می دهد "
```suggestion
"همچنین به عنوان «انواع جمع» شناخته می‌شوند، که به تایپ‌ سیستم اجازه می‌دهد "
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +"نادیده گرفتن  خروجی طولانی کامپایلر عادت کرده اند. کامپایلر Rust به طور قابل "
```suggestion
"نادیده گرفتن خروجی طولانی کامپایلر عادت کرده‌اند. کامپایلر Rust به طور قابل "
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +"توجهی پرحرف تر از سایر  کامپایلرها است. اغلب بازخوردهای _عملیاتی_ را در "
```suggestion
"توجه‌ای پرحرف‌تر از سایر کامپایلرها است. اغلب بازخوردهای _عملیاتی_ را در "
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +"اختیار شما قرار می دهد که آماده کپی و پیست کردن در کد شما هستند."
```suggestion
"اختیار شما قرار می‌دهد که آماده کپی و پیست کردن در کد شما هستند."
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +"بگیرید همراه  نیست:"
```suggestion
"بگیرید همراه نیست:"
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +"یک ژنراتور عدد تصادفی، اما <span dir=ltr>[کتابخانه `rand`](https://docs.rs/"
```suggestion
"یک تولید‌کننده عدد تصادفی، اما <span dir=ltr>[کتابخانه `rand`](https://docs.rs/"
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +"منطق پشت این امر این است که نمیتوان عملکردی را از کتابخانه استانداردحذف کرد، "
```suggestion
"منطق پشت این امر این است که نمیتوان عملکردی را از کتابخانه استاندارد حذف کرد، "
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +"بنابراین  باید بسیار مانا باشد. برای مثال‌های بالا، جامعه Rust هنوز در تلاش "
```suggestion
"بنابراین باید بسیار پایدار باشد. برای مثال‌های بالا، جامعه Rust هنوز در تلاش "
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +"است تا بهترین راه حل  را پیدا کند --- و شاید برای برخی از این موارد، یک "
```suggestion
"است تا بهترین راه حل را پیدا کند --- و شاید برای برخی از این موارد، یک "
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +"پیامدهای این امر  این است که کتابخانه استاندارد می تواند کوچکتر باشد."
```suggestion
"پیامدهای این امر این است که کتابخانه استاندارد می تواند کوچکتر باشد."
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +"به شما کمک می  کنند تا یک مورد خوب و قابل اعتماد را پیدا کنید."
```suggestion
"به شما کمک می‌کنند تا یک مورد خوب و قابل اعتماد را پیدا کنید."
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +"در IDE‌ها و ویرایشگرهای متن اصلی استفاده می شود."
```suggestion
"در IDE‌ها و ویرایشگرهای متن اصلی استفاده می‌شود."
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +msgstr "بلاک‌ها و اسکوپ‌ها با پرانتزهای باز و بسته مشخص می شوند."
```suggestion
msgstr "بلاک‌ها و اسکوپ‌ها با پرانتزهای باز و بسته مشخص می‌شوند."
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +"کامنت‌های تک خطی با ‍`//` شروع می شوند و کامنت‌های چند خطی با `/* ... */` مشخص "
```suggestion
"کامنت‌های تک خطی با ‍`//` شروع می‌شوند و کامنت‌های چند خطی با `/* ... */` مشخص "
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +"می شوند."
```suggestion
"می‌شوند."
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +msgstr "کلمات کلیدی مانند `if `و `while` به همان صورت عمل می کنند."
```suggestion
msgstr "کلمات کلیدی مانند `if `و `while` به همان صورت عمل می‌کنند."
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +msgstr "انتساب متغیر با `=` انجام می شود، مقایسه با `==` انجام می شود."
```suggestion
msgstr "انتساب متغیر با `=` انجام می‌شود، مقایسه با `==` انجام می‌شود."
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +msgstr "اعداد علامت‌دار"
```suggestion
msgstr "اعداد صحیح علامت‌دار"
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +msgstr "اعداد مثبت"
```suggestion
msgstr "اعداد صحیح مثبت"
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +msgstr "مقادیر عددی یونی‌کد"
```suggestion
msgstr "مقادیر عددی یونیکد"
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +"== \"\\\\n\"`.شما می توانید با استفاده از تعداد برابر `#` در دو طرف نقل "
```suggestion
"== \"\\\\n\"`.شما می‌توانید با استفاده از تعداد برابر `#` در دو طرف دابل‌کوت "
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +"قول‌ها، نقل قول‌های دوگانه را جاسازی کنید:"
```suggestion
"دابل‌کوت‌ها، دابل‌کوت‌ها را جاسازی کنید:"
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +"رشته‌های بایت به شما امکان می دهند مستقیماً یک مقدار <span dir=ltr>`&[u8]`</"
```suggestion
"رشته‌های بایت به شما امکان می‌دهند مستقیماً یک مقدار <span dir=ltr>`&[u8]`</"
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +"می توان همه خطوط زیرین `_` را در اعداد حذف کرد، آنها فقط برای خوانایی "
```suggestion
"می‌توان همه خطوط زیرین `_` را در اعداد حذف کرد، آنها فقط برای خوانایی "
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +"هستند.  «<span dir=ltr>`1_000`</span>  می تواند به صورت <span "
```suggestion
"هستند.  «<span dir=ltr>`1_000`</span>  می‌تواند به صورت <span "
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +"dir=ltr>`123_i64`</span> می تواند به صورت <span dir=ltr>`123i64`</span> "
```suggestion
"dir=ltr>`123_i64`</span> می‌تواند به صورت <span dir=ltr>`123i64`</span> "
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +"نظر گرفته می شوند."
```suggestion
"نظر گرفته می‌شوند."
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +"ما می توانیم از مقادیر ثابت برای انتساب مقادیر به آرایه‌ها استفاده کنیم."
```suggestion
"ما می‌توانیم از مقادیر ثابت برای انتساب مقادیر به آرایه‌ها استفاده کنیم."
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +"فرض را می  دهد، <span dir=ltr>`{:?}`</span>  خروجی دیباگ را می دهد. انواع‌ای "
```suggestion
"فرض را می‌دهد، <span dir=ltr>`{:?}`</span>  خروجی دیباگ را می‌دهد. انواع‌ای "
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +"مانند اعداد صحیح  و رشته‌ها خروجی پیش فرض را پیاده سازی می کنند، اما آرایه‌ها "
```suggestion
"مانند اعداد صحیح و رشته‌ها خروجی پیش فرض را پیاده سازی می‌کنند، اما آرایه‌ها "
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +"فقط خروجی دیباگ را پیاده  سازی می کنند. این بدان معناست که ما باید در اینجا "
```suggestion
"فقط خروجی دیباگ را پیاده سازی می‌کنند. این بدان معناست که ما باید در اینجا "
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +"فرمت «چاپ زیبا» را فراخوانی می کند که می تواند خواندن آن را آسان تر کند."
```suggestion
"فرمت «چاپ زیبا» را فراخوانی می‌کند که می‌تواند خواندن آن را آسان تر کند."
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +msgstr "تاپل‌ها"
```suggestion
msgstr ":تاپل‌ها"
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +msgstr "تاپل‌ها مقادیر انواع مختلف را در یک نوع ترکیبی کنارهم قرار می‌دهند."
```suggestion
msgstr "تاپل‌ها مقادیر انواع مختلف را در یک نوع مرکب کنار هم قرار می‌دهند."
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +"می توان به فیلدهای یک تاپل با استفاده از نقطه و شماره ایندکس مقدار، مانند "
```suggestion
"می‌توان به فیلدهای یک تاپل با استفاده از نقطه و شماره اندیس مقدار، مانند "
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +"تاپل خالی <span dir=ltr>`()`</span> همچنین به عنوان «نوع یکه» شناخته می "
```suggestion
"تاپل خالی <span dir=ltr>`()`</span> همچنین به عنوان «نوع یکه» شناخته می‌شود."
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +"شود.  این هم یک نوع است و هم تنها مقدار معتبر آن نوع - یعنی هم نوع و هم "
```suggestion
" این هم یک نوع است و هم تنها مقدار معتبر آن نوع - یعنی هم نوع و هم "
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +"مقدار آن به صورت <span dir=ltr>`()`</span> بیان می شوند.رای مثال برای نشان "
```suggestion
"مقدار آن به صورت <span dir=ltr>`()`</span> بیان می‌شوند.رای مثال برای نشان "
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +"دادن اینکه یک تابع یا عبارت هیچ مقدار برگشتی ندارد استفاده می شود، همانطور "
```suggestion
"دادن اینکه یک تابع یا عبارت هیچ مقدار برگشتی ندارد استفاده می‌شود، همانطور "
```

2023-11-03 07:57 UTC, hamidrezakp commented on po/fa.po
> +msgstr "رشته‌ها و تکرار کننده‌ها (Strings and Iterators)"
```suggestion
msgstr "رشته‌ها و تکرارکننده‌ها (Strings and Iterators)"
```

2023-11-04 14:09 UTC, hamidrezakp approved these changes
LGTM!

2023-11-04 14:11 UTC, merged