fa: Translate Part  `6.x`, `7`, `..`, `15.x`, `16.1` , `..` , `16.5`
google/comprehensive-rust pull request #1453
Opened 2023-11-08 08:54 UTC by moaminsharifi

Part of #671
Summary of changes:

- Translate Part  `6.x`, `7`, `..`, `15.x`, `16.1` , `..` , `16.5`
*for making easier for Reviewers, I just translate until `#: src/basic-syntax/references.md:3`*

2023-11-16 13:43 UTC, mgeisler commented
Hi @moaminsharifi, I see lots of translations here — should it be reviewed and merged?

2023-11-16 18:31 UTC, moaminsharifi commented
> Hi @moaminsharifi, I see lots of translations here — should it be reviewed and merged?
Sure, we need to review and merge them.

2023-11-18 07:30 UTC, hamidrezakp commented
I will review this changes tonight.

2023-11-19 17:59 UTC, hamidrezakp requested changes
Partial Review, until line 3872.
And let's discuss the translation for `Trait` in Persian. Trait is like interface in other languages. but defines certain trait that types can implement.
I suggest using `رفتار` or just ‍`تریت`, Do you have any other idea?

2023-11-19 17:59 UTC, hamidrezakp commented on po/fa.po
> +"همه موارد زبانی در Rust را می‌توان با استفاده از سینتکس ویژه  `///` داکیومنت "
```suggestion
"همه موارد زبان در راست را می‌توان با استفاده از سینتکس ویژه `///` مستند "
```

2023-11-19 17:59 UTC, hamidrezakp commented on po/fa.po
> +"شوند."
```suggestion
"کرد."
```

2023-11-19 17:59 UTC, hamidrezakp commented on po/fa.po
> +"محتوا کامنت شده به عنوان `Markdown` در نظر گرفته می‌شود. تمام جعبه‌هایی که در "
```suggestion
"محتوا کامنت شده به عنوان `Markdown` در نظر گرفته می‌شود. تمام جعبه‌هایی (Crate) که در "
```

2023-11-19 17:59 UTC, hamidrezakp commented on po/fa.po
> +"Rust منتشر می‌شوند به‌طور خودکار با استفاده از ابزار [rustdoc](https://doc."
```suggestion
"راست منتشر می‌شوند به‌طور خودکار با استفاده از ابزار [rustdoc](https://doc."
```

2023-11-19 17:59 UTC, hamidrezakp commented on po/fa.po
> +"از این الگو داکیونت شود.همچنین میتوان قطعه کدهایی شامل نحوه استفاده را "
```suggestion
"از این الگو مستند شود. همچنین میتوان قطعه کدهایی شامل نحوه استفاده را "
```

2023-11-19 17:59 UTC, hamidrezakp commented on po/fa.po
> +"داکیومنت کرد و به عنوان تست‌های واحد (unit tests) استفاده خواهند شد."
```suggestion
"مستند کرد و به عنوان تست‌های واحد (unit tests) استفاده خواهند شد."
```

2023-11-19 17:59 UTC, hamidrezakp commented on po/fa.po
> +"دانشجویان را با داکیومنت‌های تولید شده برای جعبه `rand` در [`docs.rs/rand`]"
The phrasing is not the same as original text, can you please edit it as it is?
And lets use `مستند` for ‍`Document` instead of ‍`داکیومنت`

2023-11-19 17:59 UTC, hamidrezakp commented on po/fa.po
> +"متدها تابع‌هایی هستند که به یک نوع خاص هستند. آرگومان `self` یک متد، نمونه‌ای "
```suggestion
"متدها، تابع‌هایی مربوط به یک نوع خاص هستند. آرگومان `self` یک متد، نمونه‌ای "
```

2023-11-19 17:59 UTC, hamidrezakp commented on po/fa.po
> +"در حالی که از _نظر فنی_  زبان Rust یک متد سازنده خاص ندارد، معمولاً  از "
```suggestion
"در حالی که از _نظر فنی_  راست یک متد سازنده خاص ندارد، معمولاً  از "
```

2023-11-19 17:59 UTC, hamidrezakp commented on po/fa.po
> +"متدهای استاتیک برای مقداردهی اولیه ساختارها  استفاده می‌شود (اما الزامی "
```suggestion
"متدهای استاتیک برای مقداردهی اولیه ساختارها استفاده می‌شود (اما الزامی "
```

2023-11-19 17:59 UTC, hamidrezakp commented on po/fa.po
> +"را می‌تواند  به طور مستقیم فراخوانی کرد. برای اطلاعات بیشتر [Rustnomicon]"
```suggestion
"را می‌توان به طور مستقیم فراخوانی کرد. برای اطلاعات بیشتر [Rustnomicon]"
```

2023-11-19 17:59 UTC, hamidrezakp commented on po/fa.po
> +"بگیرند،   با ارگمان‌های یک سازنده <span dir=ltr>`Rectangle::square(width: "
```suggestion
"بگیرند،   با ارگمان‌های یک سازنده <span dir=ltr>`Rectangle::square(width: "
```

2023-11-19 17:59 UTC, hamidrezakp commented on po/fa.po
> +msgstr "سربارگذاری پشتیبانی نمیشود, چون:"
Why we need the `چون` ?

2023-11-19 17:59 UTC, hamidrezakp commented on po/fa.po
> +msgstr "هر تابع پیاده سازی یکتایی دارد:"
Single != Unique
```suggestion
msgstr "هر تابع فقط یک پیاده سازی دارد:"
```

2023-11-19 17:59 UTC, hamidrezakp commented on po/fa.po
> +msgstr "همیشه یک مجموعه واحد از انواع آرگومان‌ها ار می‌گیرد."
```suggestion
msgstr "همیشه یک مجموعه واحد از انواع آرگومان‌ها را می‌گیرد."
```

2023-11-19 17:59 UTC, hamidrezakp commented on po/fa.po
> +msgstr "مقادیر پیش فرض پشتیبانی نمی شوند:"
```suggestion
msgstr "مقادیر پیش‌فرض پشتیبانی نمی‌شوند:"
```

2023-11-19 17:59 UTC, hamidrezakp commented on po/fa.po
> +msgstr "گاهی اوقات از ماکروها به عنوان جایگزین این کار استفاده می‌شود."
```suggestion
msgstr "گاهی اوقات از ماکروها به عنوان جایگزین استفاده می‌شود."
```

2023-11-19 17:59 UTC, hamidrezakp commented on po/fa.po
> +"می تواند نوعی چندشکلی (polymorphism) محدود در انواع آرگومان‌ها فراهم کند. "
```suggestion
"می‌تواند نوعی چندشکلی (polymorphism) محدود در انواع آرگومان‌ها فراهم کند. "
```

2023-11-19 17:59 UTC, hamidrezakp commented on po/fa.po
> +msgstr "روز اول: تمرین‌های صبحگاه"
```suggestion
msgstr "روز اول: تمرین‌های صبح"
```

2023-11-19 17:59 UTC, hamidrezakp commented on po/fa.po
> +msgstr "در این تمرین‌ها، دو بخش از Rust را بررسی خواهیم کرد:"
```suggestion
msgstr "در این تمرین‌ها، دو بخش از راست را بررسی خواهیم کرد:"
```

2023-11-19 17:59 UTC, hamidrezakp commented on po/fa.po
> +msgstr "تبدیل‌های صریح بین انواع"
Explicit means `صریح‍` while Implicit is the opposite: ‍`ضمنی`
```suggestion
msgstr "تبدیل‌های ضمنی بین انواع"
```

2023-11-19 17:59 UTC, hamidrezakp commented on po/fa.po
> +"در صورت امکان، از نصب محلی Rust استفاده کنید. از این طریق می‌توانید از تکمیل "
```suggestion
"در صورت امکان، از نصب محلی راست استفاده کنید. از این طریق می‌توانید از تکمیل "
```

2023-11-19 17:59 UTC, hamidrezakp commented on po/fa.po
> +"خودکار در ویرایشگر خود استفاده کنید.  برای جزئیات بیشتر در مورد نصب Rust، "
```suggestion
"خودکار در ویرایشگر خود استفاده کنید.  برای جزئیات بیشتر در مورد نصب راست، "
```

2023-11-19 17:59 UTC, hamidrezakp commented on po/fa.po
> +"قطعه کدها به صورت عمدی قابل ویرایش با ماندگاری تغییرات نیستند: قطعه کدهای "
```suggestion
"قطعه کدها به صورت عمدی قابل ویرایش نیستند: قطعه کدهای "
```

2023-11-19 17:59 UTC, hamidrezakp commented on po/fa.po
> +"درون‌خطی اگر از صفحه خارج شوید،  به حالت پیش‌فرض  بازنشانی می‌شوند و تغییرات "
```suggestion
"درون‌خطی اگر از صفحه خارج شوید،  به حالت پیش‌فرض بازنشانی می‌شوند و تغییرات "
```

2023-11-19 17:59 UTC, hamidrezakp commented on po/fa.po
> +"Rust به طور خودکار تبدیل‌های صریح بین انواع را اعمال نمی‌کند ([برخلاف زبان "
```suggestion
"راست به طور خودکار تبدیل‌های صریح بین انواع را اعمال نمی‌کند ([برخلاف زبان "
```

2023-11-19 17:59 UTC, hamidrezakp commented on po/fa.po
> +"implicit_conversion)).به عنوان مثال میتونید این رو توی یک برنامه ببنید:"
```suggestion
"implicit_conversion)).به عنوان مثال میتوانید این را در یک برنامه ببینید:"
```

2023-11-19 17:59 UTC, hamidrezakp commented on po/fa.po
> +"همه انواع عدد صحیح Rust، ویژگی‌های [<span dir=ltr>`Into<T>`</span>](https://"
```suggestion
"همه انواع عدد صحیح راست، تریت‌های (Trait) [<span dir=ltr>`Into<T>`</span>](https://"
```

2023-11-19 17:59 UTC, hamidrezakp commented on po/fa.po
> +"می‌کنندتا به ما امکان تبدیل بین انواع عددی صحیح را فراهم کنند. با پیاده سازی "
```suggestion
"می‌کنند تا به ما امکان تبدیل بین انواع عددی صحیح را بدهند. با پیاده سازی "
```

2023-11-19 17:59 UTC, hamidrezakp commented on po/fa.po
> +"dir=ltr>`from()`</span>  را دارند.  با پیاده سازی ویژگی <span "
```suggestion
"dir=ltr>`from()`</span> را دارند. با پیاده‌سازی تریت <span "
```

2023-11-19 17:59 UTC, hamidrezakp commented on po/fa.po
> +"dir=ltr>`into()`</span> را دارند. پیاده‌سازی این ویژگی‌ها راهی است که یک نوع "
```suggestion
"dir=ltr>`into()`</span> را دارند. پیاده‌سازی این تریت‌ها راهی است که یک نوع "
```

2023-11-19 18:56 UTC, moaminsharifi commented on po/fa.po
> +msgstr "سربارگذاری پشتیبانی نمیشود, چون:"
because " Each function has a single implementation:"

2023-11-19 19:04 UTC, moaminsharifi commented on po/fa.po
> +"دانشجویان را با داکیومنت‌های تولید شده برای جعبه `rand` در [`docs.rs/rand`]"
Thanks, I'll use `مستندات`  for it.

2023-11-19 19:08 UTC, moaminsharifi commented
> Partial Review, until line 3872. And let's discuss the translation for `Trait` in Persian. Trait is like interface in other languages. but defines certain trait that types can implement. I suggest using `رفتار` or just ‍`تریت`, Do you have any other idea?

I like to use `رفتار` for it. It's seems meaningful to me.

2023-11-19 19:11 UTC, hamidrezakp commented
> > Partial Review, until line 3872. And let's discuss the translation for `Trait` in Persian. Trait is like interface in other languages. but defines certain trait that types can implement. I suggest using `رفتار` or just ‍`تریت`, Do you have any other idea?
> 
> I like to use `رفتار` for it. It's seems meaningful to me.

Well i don't think `رفتار` will be the good one, 
checkout [translation of ‍`Trait` in google translate](https://translate.google.com/?sl=en&tl=fa&text=trait&op=translate).

2023-11-19 19:16 UTC, hamidrezakp commented on po/fa.po
> +msgstr "سربارگذاری پشتیبانی نمیشود, چون:"
Where is the `because` part that you translated to `چون`?

2023-12-01 07:35 UTC, hamidrezakp requested changes
Review Till line 4500

2023-12-01 07:35 UTC, hamidrezakp commented on po/fa.po
> +msgstr "برنامه فوق را اجرا کنید و به خطای کامپایلر نگاه کنید."
```suggestion
msgstr "برنامه فوق را اجرا و به خطای کامپایلر نگاه کنید."
```

2023-12-01 07:35 UTC, hamidrezakp commented on po/fa.po
> +"کتابخانه استاندارد پیاده‌سازی <span dir=ltr>`From<i8> i16`</span> به نوع "
Please update the rest of paragraph yourself, it's a little hard to review this bidi lines in github.
```suggestion
"کتابخانه استاندارد یک پیاده‌سازی <span dir=ltr>`From<i8> for i16`</span> دارد "
```

2023-12-01 07:35 UTC, hamidrezakp commented on po/fa.po
> +"dir=ltr>`Into<i16>`</span>  براینوع `i8` را ایجاد می‌کند."
```suggestion
"dir=ltr>`Into<i16>`</span>  برای نوع `i8` را ایجاد می‌کند."
```

2023-12-01 07:35 UTC, hamidrezakp commented on po/fa.po
> +"کنید  تا ببینید آیا <span dir=ltr>`From<T>`</span> برای تبدیل نوع‌هاییکه "
```suggestion
"کنید  تا ببینید آیا <span dir=ltr>`From<T>`</span> برای تبدیل انواع‌ایی که "
```

2023-12-01 07:35 UTC, hamidrezakp commented on po/fa.po
> +"زبان Rust به شما این امکان می‌دهد با استفاده از کلمه کلیدی `for` بر روی "
```suggestion
"راست به شما این امکان را می‌دهد تا با استفاده از کلمه کلیدی `for` بر روی "
```

2023-12-01 07:35 UTC, hamidrezakp commented on po/fa.po
> +"از موارد فوق برای نوشتن تابع <span dir=ltr>`pretty_print`</span> که یک "
```suggestion
"از کد بالا برای نوشتن تابع <span dir=ltr>`pretty_print`</span> که یک "
```

2023-12-01 07:35 UTC, hamidrezakp commented on po/fa.po
> +"کد زیر را در <span dir=ltr><https://play.rust-lang.org/></span> کپی کنید و "
```suggestion
"کد زیر را در <span dir=ltr><https://play.rust-lang.org/></span> کپی کرده و "
```

2023-12-01 07:35 UTC, hamidrezakp commented on po/fa.po
> +msgstr "سوال جایزه"
```suggestion
msgstr "سوال جایزه‌دار"
```

2023-12-01 07:35 UTC, hamidrezakp commented on po/fa.po
> +"امکان پذیر هست؟ اگر نه چرا؟"
```suggestion
"امکان پذیر هست؟ چرا اره و چرا نه؟"
```

2023-12-01 07:35 UTC, hamidrezakp commented on po/fa.po
> +"برای دیدن یک پیاده سازی برای محیط پروداکشن به جعبه [<span dir=ltr>`ndarray`</"
```suggestion
"برای دیدن یک پیاده‌سازی با کیفیت پروداکشن به جعبه [<span dir=ltr>`ndarray`</"
```

2023-12-01 07:35 UTC, hamidrezakp commented on po/fa.po
> +"in &array`</span>  پیش‌نمایشی از مسئله مالکیت است که بعداً توی قسمت عصر به ان "
```suggestion
"in &array`</span>  پیش‌نمایشی کوچکی از مسئله مالکیت است که بعداً توی قسمت عصر به ان "
```

2023-12-01 07:35 UTC, hamidrezakp commented on po/fa.po
> +msgstr "نکات کلیدی"
```suggestion
msgstr "نکات کلیدی:"
```

2023-12-01 07:35 UTC, hamidrezakp commented on po/fa.po
> +"هدف از این اسلاید نشان دادن این است که بلوک ها در Rust دارای نوع و مقدار "
```suggestion
"هدف از این اسلاید نشان دادن این است که بلوک ها در Rust دارای نوع و مقدار هستند. "
```

2023-12-01 07:35 UTC, hamidrezakp commented on po/fa.po
> +"بازگشتی هستند."
```suggestion
```

2023-12-01 07:35 UTC, hamidrezakp commented on po/fa.po
> +msgstr "عبارت `if`"
```suggestion
msgstr "عبارات `if`"
```

2023-12-01 07:35 UTC, hamidrezakp commented on po/fa.po
> +msgstr "حلقه `for`"
```suggestion
msgstr "حلقه‌های `for`"
```

2023-12-01 07:35 UTC, hamidrezakp commented on po/fa.po
> +msgstr "حلقه `while`"
```suggestion
msgstr "حلقه‌های `while`"
```

2023-12-01 07:35 UTC, hamidrezakp commented on po/fa.po
> +msgstr "عبارت `loop`"
```suggestion
msgstr "عبارات `loop`"
```

2023-12-01 07:35 UTC, hamidrezakp commented on po/fa.po
> +msgstr "استاتیک ها و ثابت ها"
```suggestion
msgstr "متغیر‌های ایستا و ثابت"
```

2023-12-01 07:35 UTC, hamidrezakp commented on po/fa.po
> +"متغیرهای `ثابت` و `ایستاتیک` دو روش متفاوت برای ایجاد مقادیر با اسکوپ گلوبال "
```suggestion
"متغیرهای `ثابت` و `ایستا` دو روش متفاوت برای ایجاد مقادیر با اسکوپ گلوبال "
```

2023-12-01 07:35 UTC, hamidrezakp commented on po/fa.po
> +"متغیرهای ایستاتیک در طول عمر کل اجرای برنامه خواهند ماند و بنابراین منتقل "
```suggestion
"متغیرهای ایستا در طول عمر کل اجرای برنامه خواهند ماند و بنابراین منتقل "
```

2023-12-02 11:05 UTC, moaminsharifi commented on po/fa.po
> +msgstr "سربارگذاری پشتیبانی نمیشود, چون:"
in the next part We answering a  `why?` question so need to say it.

2023-12-04 16:39 UTC, prmadev reviewed
Some comments here and there.

2023-12-04 16:39 UTC, prmadev commented on po/fa.po
> +"توی حافظه ۸ بایت، ، فضای مورد نیاز برای align نیز  ۸ بایت است (بهینه‌سازی "
مثل کامنت قبل

2023-12-04 16:39 UTC, prmadev commented on po/fa.po
> +msgstr "برای کاوش بیشتر"
اگر خیلی بخوایم دقیق باشیم،‌ میشه:
(چیزهای) بیشتر برای کاوش
اما فکر نکنم خیلی ضرورت داشته باشه.

2023-12-04 16:39 UTC, prmadev commented on po/fa.po
> +"مثال پیچیده‌تر اگر می‌خواهید در مورد اتفاقی که می‌افتد زمانی که بیش از ۲۶۵ عدد "
عدد ۲۵۶ باید باشه.

2023-12-04 16:39 UTC, prmadev commented on po/fa.po
> +"`Option` است:"
اینجا چرا با دونقطه تموم شده؟ معادل انگلیسیش به نظر میاد که با نقطه تموم کرده.

2023-12-04 16:39 UTC, prmadev commented on po/fa.po
> +"می دهد همه مارد را به صورت کامل پیمایش کنیم."
من با کلمه مارد آشنا نیستم. اگر تایپوئه شاید باید درست بشه.

2023-12-06 15:47 UTC, moaminsharifi commented on po/fa.po
> +"حافظه 1 بایت، فضای مورد نیاز برای align نیز  1 بایت است,"
please add your suggestions to to code, like @hamidrezakp. thanks.

2023-12-17 10:43 UTC, hamidrezakp approved these changes

2023-12-17 10:44 UTC, merged

2023-12-19 20:35 UTC, DannyRavi reviewed
بسیار قدر دانم بابت زحمتی که بابت این ترجمه ها کشیدی.
پیشنهاد دارم که در مورد [Bidirectional text](https://en.wikipedia.org/wiki/Bidirectional_text) ها یه بررسی داشته باشی. معمولا مترجم های زبان فارسی مقاله های ویکی پیدا از این روش برای متن های ترکیبی انگلیسی و فارسی استفاده می کنند. همینطور به نظرم اون تگ های اچ تی ام ال پروسه ترجمه و اویاریش رو سخت تر میکنه.

2023-12-19 20:35 UTC, DannyRavi commented on po/fa.po
> +msgstr "مانند <span dir=ltr>C++</span>، راست دارای مراجع است:"
please used to [Bidirectional_text](https://en.wikipedia.org/wiki/Bidirectional_text) like [RLM](https://unicode-explorer.com/c/200F) for complex text. I think it's better than use "span dir =ltr".

2023-12-19 20:35 UTC, DannyRavi commented on po/fa.po
> +"<span dir=ltr>`s`</span> یک مرجع به برش i32 است. توجه داشته باشید که نوع "
"‏`s` یک مرجع به برش i32 است. توجه داشته باشید که نوع "
this is a magic of [RLM](https://unicode-explorer.com/c/200F)

2023-12-19 20:35 UTC, DannyRavi commented on po/fa.po
> +msgstr "`String` یک بافر رشته‌ای قابل تغییر است."
`‏String` یک بافر رشته‌ای قابل تغییر است.