zh-CN: SUMMARY translation
google/comprehensive-rust pull request #1779
Opened 2024-02-03 06:41 UTC by mobyw

https://github.com/google/comprehensive-rust/issues/324

2024-02-04 00:59 UTC, henrif75 requested changes

2024-02-04 00:59 UTC, henrif75 commented on po/zh-CN.po
>  msgstr "Hello World!"
```suggestion
msgstr "Hello, World"
```

2024-02-04 01:37 UTC, AgainstEntropy commented on po/zh-CN.po
> +msgstr "泛型函数"
Sorry I should have use suggestion
I think “泛型函数” will it be more consistent than "泛化函数"

2024-02-04 02:04 UTC, AgainstEntropy commented on po/zh-CN.po
> +msgstr "更多 Trait"
```suggestion
msgstr "更多特征"
```

2024-02-04 16:22 UTC, AgainstEntropy commented on po/zh-CN.po
> +msgstr "控制流结构"
```suggestion
msgstr "`let` 控制流"
```

2024-02-04 16:22 UTC, AgainstEntropy commented on po/zh-CN.po
> +msgstr "程序的内存分配"
```suggestion
msgstr "回顾：程序的内存分配"
```

2024-02-05 19:59 UTC, AgainstEntropy approved these changes

2024-02-08 01:23 UTC, henrif75 approved these changes

2024-02-08 02:49 UTC, merged

2024-02-08 02:49 UTC, henrif75 commented
Thanks!