es: CR2 Day 2 translations
google/comprehensive-rust pull request #1858
Opened 2024-02-29 01:13 UTC by henrif75

Professional translations for CR2 content.
Changes are being staged in a separate branch until all Spanish content is reviewed.

#1463 #284

2024-03-01 08:05 UTC, deavid requested changes

2024-03-01 08:05 UTC, deavid commented on po/es.po
> +"Cuando defines una función que lleva un cierre, debes usar `FnOnce` si es "
```suggestion
"Cuando defines una función que admite un closure, debes usar `FnOnce` si es "
```

2024-03-01 19:06 UTC, henrif75 commented on po/es.po
> +"pueden desestructurar con la coincidencia:"
Sounds good!

2024-03-01 19:16 UTC, henrif75 commented on po/es.po
> +"signo o convertirlo a otro de menor tamaño. Consulta los documentos y añade "
I think so, to speak up during the class. Would you suggest a better translation?

2024-03-01 19:25 UTC, deavid commented on po/es.po
> +"signo o convertirlo a otro de menor tamaño. Consulta los documentos y añade "
"Consulta los documentos y/o pregunta si tienes cualquier duda."

I doubt there's a good way to make the translation closer to the original.

2024-03-01 19:26 UTC, deavid commented
As I answered to one of your comments, I'm holding off review until I get pinged again. If you don't push any further change and want review, please ping me here, for example with a comment. Otherwise I probably will forget to check this.

2024-03-01 21:14 UTC, henrif75 commented on po/es.po
> +"signo o convertirlo a otro de menor tamaño. Consulta los documentos y añade "
Thanks @deavid I made the change.

2024-03-01 21:15 UTC, henrif75 commented
> As I answered to one of your comments, I'm holding off review until I get pinged again. If you don't push any further change and want review, please ping me here, for example with a comment. Otherwise I probably will forget to check this.

Hi @deavid All the suggestions were committed.

2024-03-02 08:39 UTC, deavid approved these changes

2024-03-03 21:50 UTC, henrif75 commented
@deavid Thanks again!

2024-03-03 21:50 UTC, merged