es: CR2 Chromium translations
google/comprehensive-rust pull request #1868
Opened 2024-03-03 21:52 UTC by henrif75

Professional translations for CR2 content.
Changes are being staged in a separate branch until all Spanish content is reviewed.

#1463 #284

2024-03-03 22:34 UTC, deavid requested changes

2024-03-03 22:34 UTC, deavid commented on po/es.po
> +"La integración hipotética de PNG y WIP puede necesitar una implementación "
```suggestion
"La integración hipotética/WIP de PNG puede necesitar una implementación "
```

2024-03-03 22:34 UTC, deavid commented on po/es.po
> +"calcular n en la serie de Fibonacci, sumar los enteros en un slice, etc."
```suggestion
"calcular el enésimo número de la serie Fibonacci, sumar los enteros en un slice, etc."
```

2024-03-03 22:34 UTC, deavid commented on po/es.po
> +msgstr "`git status debe revelar lo siguiente:"
```suggestion
msgstr "`git status` debe revelar lo siguiente:"
```

2024-03-04 02:37 UTC, henrif75 commented
@deavid Can you check whether you were logged with your personal email (that can explain the "missing CLA")?

2024-03-04 08:38 UTC, deavid commented
> @deavid Can you check whether you were logged with your personal email (that can explain the "missing CLA")?

I am always logged with my personal email. I don't use corp for GitHub. Moreover, all changes and reviews have been done from the same personal computer. There's no difference from my side.

I don't see a CLA problem, I see a format problem. One of the suggestions I gave you breaks the formatter. Can you fix?

2024-03-04 18:23 UTC, deavid commented
I see now that the CLA was failing, my bad. And after my review it is still failing. Strange.

@mgeisler do you know how we can debug this? My understanding is that I don't need to sign CLA, and I did not need to sign it for anything before - the other PRs are going smoothly.

The only thing I can think of is that there's a commit here that says "co-authored-by" and has my email. Not sure if that is the problem, that maybe Google doesn't store the association on my email but to my GitHub account.

If there's need to do, I can sign the CLA, but since I was told that I shouldn't need to do it, I'm holding doing that until we understand if that's the course of action.

2024-03-04 23:31 UTC, merged

2024-03-07 14:35 UTC, mgeisler commented
> @mgeisler do you know how we can debug this? My understanding is that I don't need to sign CLA, and I did not need to sign it for anything before - the other PRs are going smoothly.
>
> The only thing I can think of is that there's a commit here that says "co-authored-by" and has my email. Not sure if that is the problem, that maybe Google doesn't store the association on my email but to my GitHub account.

I think this is the problem: it's only `@google.com` addresses that are exempt for the CLA check. The check has [this link](https://goto.google.com/prinfo/github.com%2Fgoogle%2Fcomprehensive-rust%2Fpull%2F1868) to look further. Right now it says everything is fine, but that's probably because the commit was edited by Henri or you.

2024-03-07 15:10 UTC, deavid commented
It was edited by Henri. Told him to delete the Co-Authored or replace it with deavid@google.com

It seems that for some operations GitHub might be adding the email account linked.

If it's me who is doing the commits, I can always take care and commit as deavid@google.com, but I can't control from the UI, or what others do.

2024-03-07 15:14 UTC, mgeisler commented
Yes, you're spot on... we've seen this before with other Googlers and I don't think there is a better fix than editing the commit like this.