zh-TW: cr2 Day 1 translations
google/comprehensive-rust pull request #1886
Opened 2024-03-07 04:30 UTC by henrif75

Professional translations for CR2 content.
Changes are being staged in a separate branch until all zh-TW content is reviewed.

#1463 #684

2024-03-07 06:04 UTC, mingyc commented on po/zh-TW.po
> +"第一天的規畫是說明 Rust 的「基礎」概念，這應直接對應到其他語言中的相似概念。"
```suggestion
"第一天的規畫是說明 Rust 中能夠直接對應到其他語言的「基礎」概念。"
```

2024-03-07 06:04 UTC, mingyc commented on po/zh-TW.po
> +"後續幾天則會介紹更進階的 Rust 程式語言。"
```suggestion
"後續幾天則會介紹更進階的部分。"
```

2024-03-07 06:16 UTC, mingyc requested changes

2024-03-07 06:16 UTC, mingyc commented on po/zh-TW.po
> +msgstr "CXX 限制"
```suggestion
msgstr "CXX 的限制"
```

2024-03-07 06:16 UTC, mingyc commented on po/zh-TW.po
> +msgstr "__確保編譯期間的記憶體安全性 - 在編譯期間避免各類記憶體錯誤"
```suggestion
msgstr "__編譯期的記憶體安全性 - 在編譯期間就能避免各類記憶體錯誤"
```

2024-03-07 06:16 UTC, mingyc commented on po/zh-TW.po
> +msgstr "__不會出現未定義的執行階段行為 - Rust 陳述式的行為一律會經過指定"
```suggestion
msgstr "__不會出現未定義的執行階段行為 (undefined runtime behavior) - Rust 陳述式的行為一律會有定義"
```

2024-03-07 06:16 UTC, mingyc commented on po/zh-TW.po
> +msgstr "在「Tools」下方點選「rustfmt」選項，以「標準」方式設定程式碼格式。"
```suggestion
msgstr "在「Tools」下方點選「`rustfmt`」選項，以「標準」方式設定程式碼格式。"
```

2024-03-07 06:16 UTC, mingyc commented on po/zh-TW.po
> +"那麼整數溢位現象呢？在 C 和 C++ 中，__「帶號」整數的溢位現象實際上並未定義，"
```suggestion
"那麼整數溢位現象呢？在 C 和 C++ 中，「帶號」整數的溢位現象實際上並未定義，"
```

2024-03-07 06:16 UTC, mingyc commented on po/zh-TW.po
> +"Rust 用來代表字串的型別有兩種，稍後會深入介紹。兩者__「一律」都儲存 UTF-8 編"
```suggestion
"Rust 用來代表字串的型別有兩種，稍後會深入介紹。兩者「一律」都儲存 UTF-8 編"
```

2024-03-07 17:29 UTC, henrif75 commented
Hi @mingyc thanks for your review!
The CLA check is failing probably because you have used your personal email, can you check whether you have it associated to your corp account?

2024-03-08 04:46 UTC, mingyc commented
Weird... It used to pass the check as I always use this address... Anyway it should be resolved now.

2024-03-08 06:11 UTC, mingyc requested changes

2024-03-08 06:11 UTC, mingyc commented on po/zh-TW.po
> +msgstr "登錄為 Chromium 原始碼"
```suggestion
msgstr "提交為 Chromium 原始碼"
```

2024-03-08 06:11 UTC, mingyc commented on po/zh-TW.po
> +msgstr "讓 Crate 保持最新狀態"
```suggestion
msgstr "保持 Crate 為最新版本"
```

2024-03-08 06:11 UTC, mingyc commented on po/zh-TW.po
> +msgstr "融會貫通 - 練習"
```suggestion
msgstr "融會貫通 - 練習題"
```

2024-03-08 06:11 UTC, mingyc commented on po/zh-TW.po
> +msgstr "練習的參考答案"
```suggestion
msgstr "練習題的參考答案"
```

2024-03-08 06:11 UTC, mingyc commented on po/zh-TW.po
> +msgstr "[控制流程基本概念](../control-flow-basics.md) (40 分鐘)"
```suggestion
msgstr "[基本的控制流程概念](../control-flow-basics.md) (40 分鐘)"
```

2024-03-08 06:11 UTC, mingyc commented on po/zh-TW.po
> +msgstr "[方法和特徵](../methods-and-traits.md) (45 分鐘)"
```suggestion
msgstr "[方法 (methods) 和特徵 (traits)](../methods-and-traits.md) (45 分鐘)"
```

2024-03-08 06:11 UTC, mingyc commented on po/zh-TW.po
> +msgstr "[泛型](../generics.md) (40 分鐘)"
```suggestion
msgstr "[泛型 (generics)](../generics.md) (40 分鐘)"
```

2024-03-08 06:11 UTC, mingyc commented on po/zh-TW.po
> +msgstr "[Hello World](./hello-world.md) (15 分鐘)"
```suggestion
msgstr "[Hello, World](./hello-world.md) (15 分鐘)"
```

2024-03-08 06:11 UTC, mingyc commented on po/zh-TW.po
> +msgstr "[控制流程基本概念](./control-flow-basics.md) (40 分鐘)"
```suggestion
msgstr "[基本的控制流程概念](./control-flow-basics.md) (40 分鐘)"
```

2024-03-11 13:05 UTC, mingyc requested changes
Sorry about multiple review cycles. This should be the last one for this PR.

2024-03-11 13:05 UTC, mingyc commented on po/zh-TW.po
> +"途參照。`x_axis` 會傳回對 `point` 的參照，但 `point` 會在函式傳回時釋放，因此"
```suggestion
"途參照。`x_axis` 會傳回對 `point` 的參照，但在函式傳回時會釋放 `point` ，因此"
```

2024-03-11 22:13 UTC, henrif75 commented on po/zh-TW.po
>  "comprehensive-rust)上相同的機器，並將 `src/android/` 目錄移至 Android 開放原"
Hi @mingyc
Could you review this suggested change? I think GH mixed things up with the multiple suggestions here.
Thanks!

2024-03-12 02:37 UTC, mingyc requested changes

2024-03-12 02:37 UTC, mingyc commented on po/zh-TW.po
> +"comprehensive-rust)上相同的機器，並將 `src/android/` 目錄移至檢出的 Android "
```suggestion
"comprehensive-rust)上相同的機器，並將 `src/android/` 目錄移至檢出的 AOSP "
```

2024-03-12 02:37 UTC, mingyc commented on po/zh-TW.po
> +"移至 AOSP 的根目錄。這可確保 Android 建構系統能夠在 `src/android/` 中 看到 "
```suggestion
"根目錄下。這可確保 Android 建構系統能夠在 `src/android/` 中看到 "
```

2024-03-12 02:38 UTC, mingyc commented on po/zh-TW.po
>  "comprehensive-rust)上相同的機器，並將 `src/android/` 目錄移至 Android 開放原"
Addressed in the latest comments. You might need to reformat again.

2024-03-12 02:44 UTC, henrif75 commented on po/zh-TW.po
>  "comprehensive-rust)上相同的機器，並將 `src/android/` 目錄移至 Android 開放原"
Thanks!

2024-03-12 04:38 UTC, mingyc approved these changes

2024-03-12 04:47 UTC, merged