zh-TW: cr2 Day 2 translations
google/comprehensive-rust pull request #1889
Opened 2024-03-07 17:52 UTC by henrif75

Professional translations for CR2 content.
Changes are being staged in a separate branch until all zh-TW content is reviewed.

#1463 #684

2024-03-12 06:30 UTC, mingyc requested changes

2024-03-12 06:30 UTC, mingyc commented on po/zh-TW.po
> +"這裡的 `Box` 型別是智慧指標，我們會在本課程的後續部分詳細說明。運算式可透過 "
```suggestion
"這裡的 `Box` 型別是一種智慧指標，我們會在本課程的後續部分詳細說明。如測試中所示，運算式可被 "
```

2024-03-12 06:30 UTC, mingyc commented on po/zh-TW.po
> +"`Box::new`「裝箱」，如測試中所示。如要求裝箱運算式的值，請使用 deref 運算子 "
```suggestion
"`Box::new`「裝箱」。如要求裝箱運算式的值，請使用 deref 運算子 "
```

2024-03-12 06:30 UTC, mingyc commented on po/zh-TW.po
> +"請複製程式碼並貼到 Rust Playground，然後開始實作 `eval`。最終成品應會通過測"
```suggestion
"請複製程式碼並貼到 Rust Playground，然後開始實作 `eval`。最終成品應要通過測"
```

2024-03-12 06:30 UTC, mingyc commented on po/zh-TW.po
> +"以下是常見模式：結構體包裝一個特徵實作項目，並實作該相同特徵，在程序中加入行"
```suggestion
"以下是一種常見模式：在一個結構體中封裝一個特徵的實作，此結構體同時也實作該相同特徵，和在程序中加入行"
```

2024-03-12 06:30 UTC, mingyc commented on po/zh-TW.po
> +"使用 `as` 進行轉換，可說是採用相對鋒利的一種工具，使用上並不容易；而且要是日"
```suggestion
"雖然使用 `as` 進行型別相當簡單，但是非常容易出錯；舉例來說，"
```

2024-03-12 06:30 UTC, mingyc commented on po/zh-TW.po
> +"後的維護作業改變了所用型別或型別中值的範圍，此工具就可能會成為導致細微錯誤的"
```suggestion
"如果往後的維護作業改變了所用型別或型別中值的範圍，這常常就是某些細微錯誤的來源。"
```

2024-03-12 06:30 UTC, mingyc commented on po/zh-TW.po
> +"來源。只有在意圖用於指明無條件截斷時，我們才建議轉換。舉例來說，如果無論高位"
```suggestion
"只有在意圖用於指明無條件截斷時，我們才建議使用型別轉換。舉例來說，如果無論高位"
```

2024-03-12 06:30 UTC, mingyc commented on po/zh-TW.po
> +"元中的內容為何，您都要透過 `as u32` 選取 `u64` 的底部 32 位元，就可以這麼做。"
```suggestion
"元中的內容為何，您都只需要 `u64` 的底部 32 位元，就可以使用 `as u32`。"
```

2024-03-12 06:30 UTC, mingyc commented on po/zh-TW.po
> +"如果是 `u32` 到 `u64` 這類絕對無誤的轉換，適合先使用 `From` 或 `Into` (而非 "
```suggestion
"如果是 `u32` 到 `u64` 這類絕對無誤的型別轉換，適合先使用 `From` 或 `Into` (而非 "
```

2024-03-13 04:20 UTC, mingyc approved these changes

2024-03-13 14:25 UTC, henrif75 commented
Thank you @mingyc!

2024-03-13 14:25 UTC, merged