zh-TW: cr2 Day 3 translations
google/comprehensive-rust pull request #1890
Opened 2024-03-07 20:15 UTC by henrif75

Professional translations for CR2 content.
Changes are being staged in a separate branch until all zh-TW content is reviewed.

#1463 #684

2024-03-19 06:28 UTC, mingyc requested changes

2024-03-19 06:28 UTC, mingyc commented on po/zh-TW.po
> +msgstr "[複製型別](./memory-management/copy-types.md) (5 分鐘)"
```suggestion
msgstr "[拷貝 (Copy) 型別](./memory-management/copy-types.md) (5 分鐘)"
```

2024-03-19 06:28 UTC, mingyc commented on po/zh-TW.po
> +msgstr "有時候，您可能會「想要」__複製值。`Clone` 特徵可完成這項作業。"
```suggestion
msgstr "有時候，您可能會「想要」複製一個值。`Clone` 特徵可完成這項作業。"
```

2024-03-19 06:28 UTC, mingyc commented on po/zh-TW.po
> +"標」__："
```suggestion
"標」："
```

2024-03-19 06:28 UTC, mingyc commented on po/zh-TW.po
> +"請注意，這裡的規定是同一點上不得「存在」__衝突的參照，在何處解除參照並不重"
```suggestion
"請注意，這裡的規定是同一點上不得「存在」衝突的參照，在何處解除參照並不重"
```

2024-03-19 06:28 UTC, mingyc commented on po/zh-TW.po
> +"也會「透過」__這項約束，將程式碼最佳化。舉例來說，共用參照背後的值可以在該參"
```suggestion
"也會「透過」這項約束，將程式碼最佳化。舉例來說，共用參照背後的值可以在該參"
```

2024-03-19 06:28 UTC, mingyc commented on po/zh-TW.po
> +"這張投影片的重點是 Rust 提供「安全的」__方法，可讓您修改共用參照背後的資料。"
```suggestion
"這張投影片的重點是 Rust 提供「安全的」方法，可讓您修改共用參照背後的資料。"
```

2024-03-19 06:28 UTC, mingyc commented on po/zh-TW.po
> +msgstr "參照的「生命週期」__不得「超過」其所參照的值。此由借用檢查器負責驗證。"
```suggestion
msgstr "參照的「生命週期」不得「超過」其所參照的值。此由借用檢查器負責驗證。"
```

2024-03-19 06:28 UTC, mingyc commented on po/zh-TW.po
> +"學生可能會詢問何時該使用生命週期。Rust 的借用「一律」__具有生命週期。在大多數"
```suggestion
"學生可能會詢問何時該使用生命週期。Rust 的借用「一律」具有生命週期。在大多數"
```

2024-03-19 06:28 UTC, mingyc commented on po/zh-TW.po
> +"二元樹是一種樹狀資料結構，其中每個節點都有左右兩個子項。我們會建立每個節點都"
```suggestion
"二元樹是一種樹狀資料結構，其中每個節點都有左右兩個子節點。我們會建立每個節點都"
```

2024-03-19 06:28 UTC, mingyc commented on po/zh-TW.po
> +"照。但可能也是有某些無法完全「理解」的情況，這通常會導致「與借用檢查器衝"
```suggestion
"照。但檢查器也可能無法完全「理解」某些的情況，這通常會導致「與借用檢查器衝"
```

2024-03-19 06:28 UTC, mingyc commented on po/zh-TW.po
> +"借用檢查器在設計上涵蓋了許多常見模式，例如同時對結構體中的不同欄位進行專屬參"
```suggestion
"借用檢查器在設計上考量了許多常見模式，例如同時對結構體中的不同欄位進行專屬參"
```

2024-03-19 06:28 UTC, mingyc commented on po/zh-TW.po
> +"在某些情況下，您必須修改共用 (唯讀) 參照背後的資料。比方說，共用的資料結構可"
```suggestion
"在某些情況下，您必須修改共用 (唯讀) 參照背後的資料：比方說，共用的資料結構可"
```

2024-03-19 06:28 UTC, mingyc commented on po/zh-TW.po
> +"能含有內部快取，並想透過唯讀方法更新該快取，就屬於這種情況。"
```suggestion
"能含有內部快取，並想透過唯讀方法更新該快取。"
```

2024-03-21 04:31 UTC, mingyc requested changes

2024-03-21 04:31 UTC, mingyc commented on po/zh-TW.po
> +"熟悉垃圾收集實作的學員會知道，垃圾收集器是從一組「根」開始尋找所有可存取的記"
```suggestion
"熟悉垃圾回收實作的學員會知道，垃圾回收器是從一組「根」開始尋找所有可存取的記"
```

2024-03-21 04:31 UTC, mingyc commented on po/zh-TW.po
> +msgstr "複製"
```suggestion
msgstr "`Clone` 複製"
```

2024-03-21 18:40 UTC, henrif75 commented on po/zh-TW.po
> +#, fuzzy
Remove

2024-03-22 04:54 UTC, mingyc commented
There are some formatting issues.

2024-03-22 06:23 UTC, mingyc approved these changes

2024-03-22 13:36 UTC, henrif75 commented
@mingyc Thank you!

2024-03-22 14:42 UTC, merged