zh-TW: cr2 Day 4 translations
google/comprehensive-rust pull request #1891
Opened 2024-03-07 22:22 UTC by henrif75

Professional translations for CR2 content.
Changes are being staged in a separate branch until all zh-TW content is reviewed.

#1463 #684

2024-03-20 18:15 UTC, johnathan79717 commented
Why are there changes to `ja.po` in this PR?

2024-03-20 19:48 UTC, henrif75 commented
> Why are there changes to `ja.po` in this PR?

Good catch, that was a mistake. I'm fixing it right now, thanks for the heads up!

2024-03-29 05:27 UTC, mingyc requested changes

2024-03-29 05:27 UTC, mingyc commented on po/zh-TW.po
> +msgstr "不安全的 Rust：不能用安全的 Rust 表示時的應急方法。"
```suggestion
msgstr "不安全的 Rust：不能寫出安全的 Rust 時的應急方法。"
```

2024-03-29 05:27 UTC, mingyc commented on po/zh-TW.po
> +msgstr "[練習：盧恩演算法](./testing/exercise.md) (30 分鐘)"
```suggestion
msgstr "[練習：盧恩 (Luhn) 演算法](./testing/exercise.md) (30 分鐘)"
```

2024-04-03 04:26 UTC, mingyc approved these changes

2024-04-03 16:55 UTC, henrif75 commented
Thanks @mingyc!

2024-04-03 16:55 UTC, merged