zh-TW: cr2 Chromium translations
google/comprehensive-rust pull request #1893
Opened 2024-03-08 00:33 UTC by henrif75

Professional translations for CR2 content.
Changes are being staged in a separate branch until all zh-TW content is reviewed.

#1463 #684

2024-03-11 13:45 UTC, johnathan79717 commented
I'm interested in reviewing this since I'm part of the Chromium team.  I'll try to review it today.

2024-03-11 18:33 UTC, johnathan79717 requested changes
Reviewed until the beginning of the interoperability section.

2024-03-11 18:33 UTC, johnathan79717 commented on po/zh-TW.po
> +"在 C++ 中編寫的 `gtest` 測試，並透過 FFI 呼叫練習 Rust。如果 Rust 程式碼只是"
```suggestion
"在 C++ 中編寫的 `gtest` 測試，並透過 FFI 呼叫並執行 Rust。如果 Rust 程式碼只是"
```

2024-03-11 18:33 UTC, johnathan79717 commented on po/zh-TW.po
> +"的 C++ 單元測試，測試 C++ 和 Rust 的實作項目 (將測試參數化，方便以 "
```suggestion
"QR 在第一方 Rust 層中的功用很少 (只是精簡的 FFI 黏合工具)，因此會使用現有"
"的 C++ 單元測試，測試 C++ 和 Rust 的實作項目 (將測試參數化，方便以 "
```

2024-03-11 18:33 UTC, johnathan79717 commented on po/zh-TW.po
> +"`libpng` 提供，但缺少 `png` Crate (例如 RGBA => BGRA) 或伽馬校正。這類功能可"
```suggestion
"假設性/WIP PNG 整合可能需實作記憶體安全地像素轉換，這類像素轉換是由 "
"`libpng` 提供，但 `png` Crate 中缺少 (例如 RGBA => BGRA 或伽馬校正)。這類功能可"
```

2024-03-11 18:33 UTC, johnathan79717 commented on po/zh-TW.po
```suggestion
msgstr "測試練習"
```
This is for line 14581

2024-03-11 18:33 UTC, johnathan79717 commented on po/zh-TW.po
> +msgstr "在 Chromium 版本中："
```suggestion
msgstr "在您的 Chromium 版本中："
```

2024-03-11 18:33 UTC, johnathan79717 commented on po/zh-TW.po
> +"這項工具會自動為非 C 功能產生 FFI 替換程式 (與 C-ABI 相容的小型免費函式)，例"
```suggestion
"這項工具會自動為非 C 功能產生 FFI 替換程式 (與 C-ABI 相容的小型、可自由使用的函式)，例"
```

2024-03-11 18:33 UTC, johnathan79717 commented on po/zh-TW.po
> +"如讓 FFI 呼叫 Rust 或 C++ 方法；手動繫結會需要手動編寫這類頂層的免費功能"
```suggestion
"如讓 FFI 呼叫 Rust 或 C++ 方法；手動繫結會需要手動編寫這類頂層的、可自由使用的函式"
```

2024-03-11 18:33 UTC, johnathan79717 commented on po/zh-TW.po
> +"繫結時，`std::span<T>`/`&[T]` 必須手動解構並重新建構，而沒有指標和長度。這麼"
```suggestion
"繫結時，`std::span<T>`/`&[T]` 必須從一個指標和長度去手動解構並重新建構。這麼"
```

2024-03-11 18:33 UTC, johnathan79717 commented on po/zh-TW.po
> +msgstr "// Definitions of Rust types and functions go here\n"
```suggestion
msgstr "// 這裡放 Rust 型別和函式的定義\n"
```

2024-03-11 18:33 UTC, johnathan79717 commented on po/zh-TW.po
> +msgstr "Rust 中對 C++ `std::unique_ptr` 的原生支援"
```suggestion
msgstr "C++ 中對 Rust 切片的原生支援"
```

2024-03-11 22:29 UTC, henrif75 commented on po/zh-TW.po
> +"特定第三方 Crate 的第一方 Rust 黏合程式碼通常應儲存在 `third_party/rust/"
Since it a fuzzy entry i, the rendered page will show the original.
Can you send a PR with translation after we merge this one?

2024-03-11 22:31 UTC, henrif75 commented on po/zh-TW.po
>  #, fuzzy
Remove fuzzy.

2024-03-11 22:36 UTC, henrif75 commented on po/zh-TW.po
>  #, fuzzy
Delete fuzzy

2024-03-12 17:50 UTC, johnathan79717 commented on po/zh-TW.po
> +"特定第三方 Crate 的第一方 Rust 黏合程式碼通常應儲存在 `third_party/rust/"
Sure

2024-03-12 19:00 UTC, johnathan79717 commented on po/zh-TW.po
> +msgstr "刻意從 `#[cxx::bridge]` 中取得不相符的 C++ 函式簽章，並習慣看到錯誤。"
```suggestion
msgstr "刻意從 `#[cxx::bridge]` 中取得不相符的 C++ 函式簽章，並熟悉看到的錯誤。"
```

2024-03-12 19:01 UTC, johnathan79717 commented on po/zh-TW.po
> +"__「opaque」型別就不會，因為這種型別的大小為零。CXX 中的 trivial 型別則「有可"
```suggestion
"「opaque」型別就不會，因為這種型別的大小為零。CXX 中的 trivial 型別則「有可"
```

2024-03-12 19:01 UTC, johnathan79717 commented on po/zh-TW.po
> +"能」__造成 UB，雖然 CXX 的設計讓撰寫這類範例相當困難。"
```suggestion
"能」造成 UB，雖然 CXX 的設計讓撰寫這類範例相當困難。"
```

2024-03-12 19:10 UTC, henrif75 commented on po/zh-TW.po
>  #, fuzzy
Remove

2024-03-13 19:36 UTC, johnathan79717 approved these changes

2024-03-13 19:36 UTC, johnathan79717 commented on po/zh-TW.po
> +msgstr "您要求的工作"
```suggestion
msgstr "您需要做的"
```

2024-03-13 19:36 UTC, johnathan79717 commented on po/zh-TW.po
msgstr "產生程式碼"
for line 15555

2024-03-13 19:36 UTC, johnathan79717 commented on po/zh-TW.po
> +msgstr "修補周圍項目"
```suggestion
msgstr "撰寫修補程式"
```

2024-03-13 19:36 UTC, johnathan79717 commented on po/zh-TW.po
> +"Chromium 程式碼的依附元件，請一併加上 `allow-first-party-usage=false`。該檔案"
```suggestion
"`build-script-outputs` 新增至 Crate。若是遞移依附元件，也就是 Chromium 程式碼 "
"不應直接依附的依附元件，請一併加上 `allow-first-party-usage=false`。該檔案"
```

2024-03-13 19:36 UTC, johnathan79717 commented on po/zh-TW.po
> +"`BUILD.gn` 檔案，通知 ninja 這個輸出檔案會輸入至後續建構步驟。"
```suggestion
"`BUILD.gn` 檔案以通知 ninja 這個輸出檔案會輸入至後續建構步驟。"
```

2024-03-13 19:36 UTC, johnathan79717 commented on po/zh-TW.po
> +"使用 `cd third-party/rust/chromium_crates_io; cargo audit`，檢查是否有已知的"
```suggestion
"使用 `cd third-party/rust/chromium_crates_io; cargo audit` 檢查是否有已知的"
```

2024-03-13 19:36 UTC, johnathan79717 commented on po/zh-TW.po
> +"用 Crate。"
```suggestion
"上述內容只是指南，請與 `security@chromium.org` 的審查人員合作，瞭解如何正確地"
"確保 Crate 是可信的。"
```

2024-03-13 19:36 UTC, johnathan79717 commented on po/zh-TW.po
> +"這時，由於並非使用包容性的語言，預先提交的檢查作業可能會失敗。這是因為 Rust "
```suggestion
"這時，預先提交的檢查作業可能會因使用非包容性的語言而失敗。這是因為 Rust "
```

2024-03-13 19:36 UTC, johnathan79717 commented on po/zh-TW.po
> +"default-feature)。假設提交 Chromium 會使用 Crate，但不會用於處理不可靠的輸入"
```suggestion
"default-feature)。假設提交 Chromium 時會使用這個 Crate，但不會用於處理不可靠的輸入"
```

2024-03-13 19:36 UTC, johnathan79717 commented on po/zh-TW.po
> +msgstr "步數"
```suggestion
msgstr "步驟"
```

2024-03-13 19:36 UTC, johnathan79717 commented on po/zh-TW.po
> +"比較 UTF16 與 UTF8。學生應瞭解 Rust 字串一律為 UTF8，且可能判斷出較適合在 C+"
```suggestion
"UTF16 與 UTF8：學生應瞭解 Rust 字串一律為 UTF8，且可能判斷出較適合在 C+"
```

2024-03-14 02:32 UTC, merged