zh-TW: cr2 Bare Metal translations
google/comprehensive-rust pull request #1894
Opened 2024-03-08 00:47 UTC by henrif75

Professional translations for CR2 content.
Changes are being staged in a separate branch until all zh-TW content is reviewed.

#1463 #684

2024-04-25 16:44 UTC, johnathan79717 requested changes
Reviewed the morning part.

2024-04-25 16:44 UTC, johnathan79717 commented on po/zh-TW.po
> +"至型別系統，確保您在未事先適當設定接腳時，不會嘗試以特定方式使用接腳。在編譯"
```suggestion
"至型別系統，確保您不會在未事先適當設定時嘗試使用接腳。在編譯"
```

2024-04-25 16:44 UTC, johnathan79717 commented on po/zh-TW.po
> +"可涵蓋常見的微控制器周邊裝置。"
```suggestion
"涵蓋常見的微控制器周邊裝置。"
```

2024-04-25 16:44 UTC, johnathan79717 commented on po/zh-TW.po
> +msgstr "監控計時器"
```suggestion
msgstr "看門狗計時器"
```

2024-04-25 16:44 UTC, johnathan79717 commented on po/zh-TW.po
> +msgstr "`embedded-hal` 的 `async` 版本仍在開發中，但尚未推出穩定版。"
```suggestion
msgstr "`embedded-hal` 的 `async` 版本已在開發中，但尚未推出穩定版。"
```

2024-04-25 16:44 UTC, johnathan79717 commented on po/zh-TW.po
> +"制輸出內容，以及連結 GDB。這個指令是由專案目錄中的 `Embed.toml` 檔案來設定。"
```suggestion
"`cargo-embed` 是 Cargo 子指令，用於建構和刷新二進位檔、記錄 RTT (即時傳輸)"
"輸出內容，以及連結 GDB。這個指令是由專案目錄中的 `Embed.toml` 檔案來設定。"
```

2024-04-25 16:44 UTC, johnathan79717 commented on po/zh-TW.po
> +"ST-Link 是 STMicroelectronics 推出的一系列電路內偵錯工具，J-Link 則來自 "
```suggestion
"ST-Link 是 ST Microelectronics 推出的一系列電路內偵錯工具，J-Link 系列則來自 "
```

2024-04-25 16:44 UTC, johnathan79717 commented on po/zh-TW.po
> +msgstr "__Embed.toml："
```suggestion
msgstr "Embed.toml："
```

2024-04-25 16:44 UTC, johnathan79717 commented on po/zh-TW.po
> +"Oxide Computer Company 的微核心 RTOS，提供記憶體防護、未授權的驅動程式、IPC"
```suggestion
"Oxide Computer Company 的微核心 RTOS，提供記憶體防護、未具有特權的驅動程式、IPC"
```

2024-04-25 16:44 UTC, johnathan79717 commented on po/zh-TW.po
> +"我們將讀取 I2C 羅盤中的方向，並將讀數記錄到序列埠。如有時間，可以試著顯示在 "
```suggestion
"我們將讀取 I2C 羅盤上的方向，並將讀數記錄到序列埠。如有時間，可以試著顯示在 "
```

2024-04-25 16:44 UTC, johnathan79717 commented on po/zh-TW.po
> +msgstr "暗示："
```suggestion
msgstr "提示："
```

2024-04-25 16:44 UTC, johnathan79717 commented on po/zh-TW.po
> +"hal/struct.Twim.html) 結構體可完成此實作。"
```suggestion
"hal/struct.Twim.html) 結構體實作此特徵。"
```

2024-04-25 16:44 UTC, johnathan79717 commented on po/zh-TW.po
> +msgstr "__Cargo.toml (您應該不需要變更此項目)："
```suggestion
msgstr "Cargo.toml (您應該不需要變更此項目)："
```

2024-04-25 16:44 UTC, johnathan79717 commented on po/zh-TW.po
> +msgstr "__Embed.toml (您應該不需要變更此項目)："
```suggestion
msgstr "Embed.toml (您應該不需要變更此項目)："
```

2024-04-25 16:44 UTC, johnathan79717 commented on po/zh-TW.po
> +msgstr "__.cargo/config.toml (您應該不需要變更此項目)："
```suggestion
msgstr ".cargo/config.toml (您應該不需要變更此項目)："
```

2024-04-25 17:57 UTC, henrif75 commented
> Reviewed the morning part.

Thank you very much @johnathan79717 !

2024-05-03 16:00 UTC, johnathan79717 commented on po/zh-TW.po
>  msgid "Useful crates"
```suggestion
msgid "Useful crates"
```

2024-05-03 16:00 UTC, johnathan79717 commented on po/zh-TW.po
> +msgstr "HAL Crate"
```suggestion
msgstr "實用的 Crate"
```

2024-05-03 16:04 UTC, johnathan79717 commented on po/zh-TW.po
> +"Crate，如[先前](../alloc.md)所見。例如，我們可能會想針對 PCI BAR 分配 MMIO 空"
```suggestion
"是實作基本夥伴系統分配器的第三方 Crate。這可供 "
"[`LockedHeap`](https://docs.rs/buddy_system_allocator/0.9.0/"
"buddy_system_allocator/struct.LockedHeap.html) 實作 [`GlobalAlloc`](https://"
"doc.rust-lang.org/core/alloc/trait.GlobalAlloc.html)，以便使用標準 `alloc` "
"Crate，如[先前](../alloc.md)所見，或用來分配其他位址空間。例如，我們可能會想針對 PCI BAR 分配 MMIO 空"
```

2024-05-03 16:10 UTC, johnathan79717 commented on po/zh-TW.po
> +"__擴充功能 (如有時間)：啟用並處理因 RTC 比對而產生的中斷情形。您可以使用 "
```suggestion
"擴充功能 (如有時間)：啟用並處理因 RTC 比對而產生的中斷情形。您可以使用 "
```

2024-05-03 16:11 UTC, johnathan79717 commented on po/zh-TW.po
> +msgstr "__src/exceptions.rs (您應該只需為練習的第 3 部分變更此項目)："
```suggestion
msgstr "src/exceptions.rs (您應該只需為練習的第 3 部分變更此項目)："
```

2024-05-03 16:11 UTC, johnathan79717 commented on po/zh-TW.po
> +msgstr "__src/logger.rs (您應該不需要變更此項目)："
```suggestion
msgstr "src/logger.rs (您應該不需要變更此項目)："
```

2024-05-03 16:11 UTC, johnathan79717 commented on po/zh-TW.po
> +msgstr "__src/pl011.rs (您應該不需要變更此項目)："
```suggestion
msgstr "src/pl011.rs (您應該不需要變更此項目)："
```

2024-05-03 16:11 UTC, johnathan79717 commented on po/zh-TW.po
> +msgstr "__build.rs (您應該不需要變更此項目)："
```suggestion
msgstr "build.rs (您應該不需要變更此項目)："
```

2024-05-03 16:12 UTC, johnathan79717 commented on po/zh-TW.po
> +msgstr "__entry.S (您應該不需要變更此項目)："
```suggestion
msgstr "entry.S (您應該不需要變更此項目)："
```

2024-05-03 16:12 UTC, johnathan79717 commented on po/zh-TW.po
> +msgstr "__exceptions.S (您應該不需要變更此項目)："
```suggestion
msgstr "exceptions.S (您應該不需要變更此項目)："
```

2024-05-03 16:12 UTC, johnathan79717 commented on po/zh-TW.po
> +msgstr "__idmap.S (您應該不需要變更此項目)："
```suggestion
msgstr "idmap.S (您應該不需要變更此項目)："
```

2024-05-03 16:12 UTC, johnathan79717 commented on po/zh-TW.po
> +msgstr "__image.ld (您應該不需要變更此項目)："
```suggestion
msgstr "image.ld (您應該不需要變更此項目)："
```

2024-05-03 16:12 UTC, johnathan79717 commented on po/zh-TW.po
> +msgstr "__Makefile (您應該不需要變更此項目)："
```suggestion
msgstr "Makefile (您應該不需要變更此項目)："
```

2024-05-03 21:44 UTC, merged