Speaker Notes for tuple-structs
google/comprehensive-rust pull request #197
Opened 2023-01-20 19:12 UTC by cchiw

2023-02-07 07:38 UTC, mgeisler requested changes

2023-02-07 07:38 UTC, mgeisler commented on src/structs/tuple-structs.md
> +* You can demonstrate how to create and modify a tuple struct. You can also add a `f64` value to the tuple struct.
Please take out the `can` twice in this line.

2023-02-07 07:38 UTC, mgeisler commented on src/structs/tuple-structs.md
> +  * This can be a good time to talk about unwrapping.  Rust generally doesn’t like inexplicit things, for instance booleans aren’t used as integers. Similarly using the data in a struct requires acce
Please take out the `can be` part: add background information or instructions directly instead of suggesting things.

2023-02-07 07:38 UTC, mgeisler commented on src/structs/tuple-structs.md
> +  * If appropriate, you might bring up that using existing operations on these new types, such as `+` is possible, and we’ll learn about generics on Day 3.
Please call this "operator overloading" instead of "using existing operations".

2023-02-09 21:02 UTC, qwandor approved these changes

2023-02-09 23:45 UTC, cchiw commented
Eek sorry for the ping @qwandor. It actually needs @mgeisler's approval since he requested changes.

2023-02-13 15:28 UTC, mgeisler commented on src/structs/tuple-structs.md
> +  *  Operator overloading is discussed on Day 3 (generics).
These forward statements will become a pain to maintain, so I would prefer if we avoid them.

2023-02-13 15:31 UTC, merged