feat: Playground - Vietnamese translation
google/comprehensive-rust pull request #2047
Opened 2024-05-03 06:02 UTC by ndminhvn

Here is the translation of ***Playground***.

2024-05-04 13:39 UTC, vohoanglong0107 commented on po/vi.po
> +msgstr "Nơi thử nghiệm (*Playground*)"
I suggest using "Sân chơi" as a translation of "Playground". "Nơi thử nghiệm" sounds too gloomy for me (more like a test site than a playground"

2024-05-04 13:54 UTC, vohoanglong0107 commented on po/vi.po
> +"[Nơi thử nghiệm Rust (*Rust Playground*)](https://play.rust-lang.org/) cung "
```suggestion
"[Sân chơi cho Rust (*Rust Playground*)](https://play.rust-lang.org/) cung "
```

2024-05-04 14:15 UTC, vohoanglong0107 commented on po/vi.po
> +"cấp một cách dễ dàng để chạy các chương trình Rust ngắn, và là cơ sở cho các "
`cung cấp một cách dễ dàng để chạy các chương trình Rust ngắn` sounds too machine like. I suggest something along the line of `cho phép ta chạy thử những đoạn code ngắn viết bằng Rust`.
Also, `là cơ sở cho các ví dụ và bài tập trong khóa học này` is a little bit hard to understand. What about `cho phép ta chạy thử những đoạn code ngắn viết bằng Rust, đặc biệt là các ví dụ và bài tập trong khoá học này`?

2024-05-04 14:24 UTC, vohoanglong0107 commented on po/vi.po
> +"world”. Nó đi kèm với một vài tính năng hữu ích:"
It's not clear what `Nó` mean in this context. I suggest the following:
```suggestion
"ví dụ và bài tập trong khóa học này. Hãy thử chạy chương trình “hello-"
"world” được hiển thị khi mở Rust Playground. Chương trình này cho ta thấy một vài tính năng hữu ích của Rust Playground"
```

2024-05-04 14:34 UTC, vohoanglong0107 commented on po/vi.po
> +"trong mục “Gỡ lỗi (*Debug*)” ở phía trên."
`extra runtime checks` should be translated to `thêm nhiều thông tin hỗ trợ trong quá trình chạy`. The same should be applied for `fewer runtime checks`

2024-05-04 14:37 UTC, vohoanglong0107 commented on po/vi.po
> +"mọi thứ trong phần còn lại của khoá học. Điều này đặc biệt hữu ích cho những "
```suggestion
"Hãy khuyến khích học viên sử dụng Rust Playground để thử nghiệm trong giờ giải lao."
"Khuyến khích học luôn giữ tab mở và liên tục thử nghiệm mọi thứ trong suốt"
"phần còn lại của khoá học. Điều này đặc biệt hữu ích cho những "
```

2024-05-04 14:39 UTC, vohoanglong0107 commented
Sorry, I should have combined all of them into a single review 😅 Got too caught up in the middle of the review

2024-05-06 16:44 UTC, qu-ngx requested changes
@ndminhvn you better review and resolve the laid-out issues first before we proceed further

2024-05-06 17:16 UTC, ndminhvn commented
Thanks @vohoanglong0107 for your suggestions. @qu-ngx I'll get it done EOD

2024-05-06 20:33 UTC, ndminhvn commented
Hi @qu-ngx, I've resolved all the comments. Please take a look. Thanks!

2024-05-06 21:39 UTC, qu-ngx approved these changes
Looks LGTM!

2024-05-06 21:42 UTC, qu-ngx commented
> Hi @qu-ngx, I've resolved all the comments. Please take a look. Thanks!

Before merging the PR, I want to make sure everything runs smoothly. @ndminhvn Did you try generating the docs to see if there is no issue left?

2024-05-07 13:13 UTC, merged