Remove error handling from protobuf exercise
google/comprehensive-rust pull request #2109
Opened 2024-05-31 00:08 UTC by randomPoison

The protobuf exercise is one of the more complicated exercises, and it comes before the section on error handling in Rust. I think that makes the error handling within the exercise more confusing for students, and adds to the cognitive burden for doing the exercise. As a potential way to address this, this PR removes the `Result`-based error handling in the exercise and replaces it with panics. This makes the code less idiomatic in Rust, but potentially more friendly to students because they don't need to worry about `Result` or error handling.

That said, I'm not entirely sure this is actually an improvement. The simpler thing might be to briefly describe the `?` operator to students so that they know they can use `?` to unwrap errors when calling functions like `parse_varint`. I'm not sure what the best approach is, so I'm open to suggestions here.

2024-05-31 11:18 UTC, mgeisler commented
Hi Nicole, thanks for catching this!

> The simpler thing might be to briefly describe the `?` operator to students so that they know they can use `?` to unwrap errors when calling functions like `parse_varint`. I'm not sure what the best approach is, so I'm open to suggestions here.

I think I like that idea: it fits with the spiral concept of visiting the same things multiple times. Here we could just show the expansion from [29.2. Try Operator](https://google.github.io/comprehensive-rust/error-handling/try.html) and tell people "we'll come back to this, think of it as an early return".

2024-05-31 13:58 UTC, djmitche commented
I suspect this was an ordering dependency we missed when re-shuffling the content. 

This particular exercise has a good bit more error-handling code than just `?` and `Result` -- I lean toward adopting @randomPoison's fix here. Maybe a comment pointing forward to the Error Handling segment would help defer any questions or misperceptions from students.

2024-06-03 16:57 UTC, mgeisler commented
> This particular exercise has a good bit more error-handling code than just `?` and `Result` -- I lean toward adopting @randomPoison's fix here. 

Good point, I'm happy with that too!

2024-06-03 16:58 UTC, mgeisler approved these changes
Thanks! Let's get this merged, preferably with a comment pointing to the error handling part like Dustin suggests.

2024-06-03 17:09 UTC, djmitche requested changes
(re-flag me for review when the comment is added)

2024-06-05 22:59 UTC, randomPoison commented
@djmitche I added a speaker note calling ahead to the error handling section. Let me know if that's not what you had in mind though!

2024-06-06 12:30 UTC, djmitche approved these changes

2024-06-07 16:13 UTC, merged