day 1
google/comprehensive-rust pull request #2238
Opened 2024-07-20 11:29 UTC by alix1383

- **sync #2038 pr**
- **add #2127 changes**

2024-07-20 12:36 UTC, DannyRavi approved these changes
there is no Error.

2024-07-20 19:07 UTC, DannyRavi requested changes
Thank you for the translations, please, the average translations should be about 100 lines or translations so that the translated text can be reviewed better.

2024-07-20 19:07 UTC, DannyRavi commented on po/fa.po
> +msgstr "35 دقیقه"
بهتره از کیبورد استاندارد فارسی استفاده بشه و اعادا به فارسی باشه
مثلا ۳۵ و نه 35

2024-07-20 19:07 UTC, DannyRavi commented on po/fa.po
> +msgstr "خوش آمد"
خوش آمدید درست تره
بهتره ترجمه کلمه به کلیمه نباشه و گر چیز به فارسی متداول هست اون معنی متداول رو بیاری

2024-07-20 19:07 UTC, DannyRavi commented on po/fa.po
> +msgstr "این بخش باید حدود 35 دقیقه طول بکشد. آن شامل:"
این شاملِ

2024-07-20 20:00 UTC, alix1383 commented on po/fa.po
> +msgstr "چندتایی‌ها(Tuples) و آرایه‌ها"
یکی از دوستان گفتن چنتایی بهتره و چون قراره به فارسی باشه همون چنتایی بنظرم اوکی باشه

https://github.com/google/comprehensive-rust/pull/2038#discussion_r1631251197

2024-07-20 20:10 UTC, alix1383 commented
از اینکه وقت گذاشتین ممنونم @DannyRavi 
مورد اول دلیل حذف شدن بعضی از عبارات کن کنم msgmerge بوده باشه برام خودمم عجیب بود 
مورد بعدی اینکه با توجه به توصیه های شما بهتره که 2 بخش اول رو دوباره چک کنم و ترجمه مناسب تری رو اراعه بدم البته بعد از merge  شدن این pr

2024-07-20 20:39 UTC, DannyRavi commented
@alix1383 
املای نانوشته بدون خطا و ایراد هست.
لطفاً موارد خطا را برطرف کنید تا این pull request رو merge کنم.
همینطور بهتر هست مبحث مورد ترجمه در آینده رو انتخاب و reserve کنید، تا با افراد دیگه که روی این پروژه کار می‌کنند، تداخل نداشته باشید.
Good luck.

2024-07-20 20:44 UTC, DannyRavi approved these changes
now it's ok.

2024-07-20 21:03 UTC, DannyRavi commented
@alix1383 please resolve 
Error formatting /home/runner/work/comprehensive-rust/comprehensive-rust/po/fa.po. Message: Child process exited with code 1: <stdin>:20355: duplicate message definition...

2024-07-22 15:36 UTC, DannyRavi commented on package.json
just use `git add ` on fa.po file. never  use `git add` and pushed any other files.

2024-07-22 15:37 UTC, DannyRavi requested changes
just push fa.po

2024-07-22 19:02 UTC, DannyRavi approved these changes

2024-07-23 10:02 UTC, moaminsharifi commented on po/fa.po
> +msgstr "مقدارها"
I think It's better to use "مقادیر" for it.  in computer science normally we use "مقادیر".

2024-07-23 10:28 UTC, moaminsharifi requested changes
After nearly 10 months away, I'm excited to be returning to active contributions. I aim to review up to 3000 pull requests.

Please avoid deleting translations and consider leaving them empty as suggested by @DannyRavi.

Thank you for your contributions.

2024-07-23 10:28 UTC, moaminsharifi commented on po/fa.po
> +msgstr "چندتایی‌ها"
I agree, normally we use "تاپل" for "tuple"

2024-07-23 10:28 UTC, moaminsharifi commented on po/fa.po
> +msgstr "مراجع مشترک"
It's a Reference which shared between two things. so "اشتراکی" is better for it.

2024-07-23 10:28 UTC, moaminsharifi commented on po/fa.po
> +msgstr "برش ها: `&[T]`"
I think I will render badly with considering #1413 
Also Please use half-space between "برش" and "ها" like "برش‌ها"

2024-07-23 10:28 UTC, moaminsharifi commented on po/fa.po
> -msgstr "تطبیق الگو"
I think "تطبیق" is better for it, dude to other translation in the computer science.

2024-07-23 10:28 UTC, moaminsharifi commented on po/fa.po
> +msgstr "تطابق مقدارها"
I think " تطبیق مقادیر" is better for it, dude to other translation in the computer science.

2024-07-23 10:28 UTC, moaminsharifi commented on po/fa.po
> +msgstr "مقادیر شمارشی"
For consistency, I recommend not translating 'Enum' throughout the book.

2024-07-23 10:28 UTC, moaminsharifi commented on po/fa.po
> -msgstr "تخریب Enumها"
due to line 254 comment I think "Enum‌های تفکیک‌پذیر" is better for it.
It's not like old-school `destructure C` function, I more like "[Destructuring assignment in JavaScript](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment)"

2024-07-23 10:28 UTC, moaminsharifi commented on po/fa.po
> +msgstr "کنترل جریان (Let)"
Please don't use `(` and `)` just `Let`

2024-07-23 10:28 UTC, moaminsharifi commented on po/fa.po
> +msgstr "توابع جنریک"
Add "تمرین"  to start of string

2024-07-23 10:28 UTC, moaminsharifi commented on po/fa.po
> +msgstr "کتابخانه‌ استاندارد تایپ ها"
Please don't change "انواع داده" to "تایپ ها"

2024-07-23 10:28 UTC, moaminsharifi commented on po/fa.po
> -msgstr "چرخه حیات"
I think "چرخه حیاط" make more sense for it, because it has  `start .... > end`

2024-07-23 10:28 UTC, moaminsharifi commented on po/fa.po
> -msgstr "اجرای نمونه کدی که بر روی آن قرار گرفته است."
where is `<kbd>Ctrl + Enter</kbd>`?

2024-07-23 10:28 UTC, moaminsharifi commented on po/fa.po
> +msgstr "برنامه"
I am not sure "برنامه" which use for "application" is a good choice for it.

2024-07-23 18:52 UTC, DannyRavi commented
@alix1383 I think you `commit` a part of content with different git username or email in your local machine or use another machine to commit and pull request. so cla/google has problem with your pull request and show `Missing CLA from one or more contributors`.

2024-07-23 19:27 UTC, DannyRavi commented
me and @javad-jafari started this project when there was no Persian language development for this project.
Fortunately, after some time, new people volunteered for the Persian part of this project, and Javad and I thought that it would be better for the new volunteers to continue and finish the translation.

But now in my opinion, without coordination and cooperation with each other, the Persian translation of this book may not be successful.

I suggest that we have a channel on Telegram and a [project](https://github.com/orgs/farsi-tools/projects/2/views/1) on GitHub to manage and clarify the tasks and do them to finish this book.
We do not get results without organization!

@javad-jafari  @alix1383 @moaminsharifi @hamidrezakp  @mehrad77
what is your opinion?

2024-07-23 19:45 UTC, javad-jafari commented on po/fa.po
> -msgstr "چرخه حیات"
but "حیاط" means Yard

2024-07-23 19:52 UTC, javad-jafari commented on po/fa.po
> +msgstr "برنامه"
the "زمان بندی" is better

2024-07-24 04:45 UTC, moaminsharifi commented
> me and @javad-jafari started this project when there was no Persian language development for this project. Fortunately, after some time, new people volunteered for the Persian part of this project, and Javad and I thought that it would be better for the new volunteers to continue and finish the translation.
> 
> But now in my opinion, without coordination and cooperation with each other, the Persian translation of this book may not be successful.
> 
> I suggest that we have a group on Telegram and a [project](https://github.com/orgs/farsi-tools/projects/2/views/1) on GitHub to manage and clarify the tasks and do them to finish this book. We do not get results without organization!
> 
> @javad-jafari @alix1383 @moaminsharifi @hamidrezakp @mehrad77 what is your opinion?


I agree that translation progress has been slow. I started contributing to the translation about a year ago, but the lack of reviewers has significantly impacted the process.

I'm eager to help accelerate the translation process. Let's create a plan to streamline the translation workflow.

2024-07-24 06:38 UTC, alix1383 commented
![image](https://github.com/user-attachments/assets/eda491b6-220d-4d0e-b276-d78551bc8385)
این صفحه به درستی رندر نمیشه به (فارسی ترجمه نمیشه)

2024-07-24 07:54 UTC, DannyRavi commented
> > me and @javad-jafari started this project when there was no Persian language development for this project. Fortunately, after some time, new people volunteered for the Persian part of this project, and Javad and I thought that it would be better for the new volunteers to continue and finish the translation.
> > But now in my opinion, without coordination and cooperation with each other, the Persian translation of this book may not be successful.
> > I suggest that we have a group on Telegram and a [project](https://github.com/orgs/farsi-tools/projects/2/views/1) on GitHub to manage and clarify the tasks and do them to finish this book. We do not get results without organization!
> > @javad-jafari @alix1383 @moaminsharifi @hamidrezakp @mehrad77 what is your opinion?
> 
> I agree that translation progress has been slow. I started contributing to the translation about a year ago, but the lack of reviewers has significantly impacted the process.
> 
> I'm eager to help accelerate the translation process. Let's create a plan to streamline the translation workflow.

I don't think the problem is with the reviewers.
In my opinion, for cooperation and successful completion of this project, this group for this project on [Telegram](https://t.me/+HAKbn2dKIqQ3NTQ0) and this [board](https://github.com/orgs/farsi-tools/projects/2/views/1) on GitHub can be effective.
Please [join this group](https://t.me/+HAKbn2dKIqQ3NTQ0).
Thanks.

@javad-jafari @alix1383 @moaminsharifi @hamidrezakp @mehrad77

2024-07-24 19:27 UTC, closed without merging