[fa] day 2 afternoon
google/comprehensive-rust pull request #2267
Opened 2024-08-07 15:41 UTC by alix1383

2024-08-07 15:47 UTC, alix1383 commented
Can we now add Farsi to the [translations page](https://google.github.io/comprehensive-rust/running-the-course/translations.html) ?

https://github.com/google/comprehensive-rust/blob/main/TRANSLATIONS.md#incomplete-translations

@DannyRavi @javad-jafari

2024-08-07 16:14 UTC, DannyRavi commented
> Can we now add Farsi to the [translations page](https://google.github.io/comprehensive-rust/running-the-course/translations.html) ?
> 
> https://github.com/google/comprehensive-rust/blob/main/TRANSLATIONS.md#incomplete-translations
> 
> @DannyRavi @javad-jafari

Maybe it can be placed in the incomplete parts

2024-08-07 16:23 UTC, DannyRavi requested changes
please resolve some parts!

2024-08-07 16:23 UTC, DannyRavi commented on po/fa.po
> +"مشابه با محدودیت‌های trait، می‌توان از نحو `impl Trait` در آرگومان‌های تابع و "
نحو -> no
syntax -> is better

2024-08-07 16:23 UTC, DannyRavi commented on po/fa.po
> +"این trait‌ها از مقایسه بین مقادیر پشتیبانی می‌کنند. همه‌ی این trait‌ها را می‌توان "
please recheck this part.

2024-08-08 08:05 UTC, DannyRavi approved these changes

2024-08-08 09:14 UTC, merged