Lecture notes for Destructing Arrays
google/comprehensive-rust pull request #266
Opened 2023-01-24 02:15 UTC by cchiw

2023-01-24 08:06 UTC, mgeisler requested changes
Let's make the notes

1. Expand on the content with extra background. Perhaps we can explain if using pattern matching is more/less expensive than using the equivalent `if` expressions?
2. Give precise tips for the instructor on what to do.

2023-01-24 08:06 UTC, mgeisler commented on src/pattern-matching/destructuring-arrays.md
> +* Continuing our journey in pattern matching, this slide just shows another type that can destructured with pattern matching.
Let's take this line out: it's more narrative than a "key point" for the instructor.

2023-01-24 08:06 UTC, mgeisler commented on src/pattern-matching/destructuring-arrays.md
> +* This is a another great time to do some live coding. You can add/remove values from the array, compare the syntax `..` and `_`, and share any errors you get.
Can you update this with precise instructions on what to do?

Please make sure that the notes _add_ to the slide. They should explain things to people who don't have an instructor around as well as tell the instructor what they should focus on.

2023-01-24 19:24 UTC, cchiw commented
updated, let me know what you think

2023-02-21 20:05 UTC, cchiw commented
soft ping. @mgeisler it needs your approval since you opened the change request.

2023-02-22 12:41 UTC, mgeisler approved these changes
Sure, let's get this in.

2023-02-22 12:41 UTC, merged