Fix raw pointer example which has UB
google/comprehensive-rust pull request #308
Opened 2023-01-31 19:50 UTC by mgeisler

The raw pointer example looks safe, but Miri flags it as having undefined behavior. This is a followup to the discussion in #177.

2023-02-02 11:07 UTC, qwandor commented
If triggers undefined behaviour then we shouldn't have it as an example, but I'm not clear on why it is UB.

2023-02-23 00:16 UTC, riking commented
The two-phase borrows mechanic means that `r1` is considered inactive until it's used to write through, and that write pops `r2` off the borrow stack.

2023-03-01 14:10 UTC, mgeisler commented
> The two-phase borrows mechanic means that `r1` is considered inactive until it's used to write through, and that write pops `r2` off the borrow stack.

Thanks @riking!

@qwandor, I would like to merge this so we can warn people against the example. The other examples in this section are similarly full of things not to do, so it fits into the theme.

2023-03-07 14:31 UTC, mgeisler commented
Hi @gendx, I think you've played a lot with unsafe... can you review this? Thanks :smile:

2023-03-07 14:37 UTC, gendx approved these changes

2023-03-07 14:40 UTC, qwandor requested changes
The point of the page was to show how to use raw pointers safely, and how safety comments should look. I think introducing Miri at this point is just going to be confusing. We should write an example that is valid instead.

2023-03-07 14:44 UTC, gendx commented
> We should write an example that is valid instead.

How about something like this:

```rust
fn main() {
    let mut array = [5, 6];
    let r1 = &mut array[0] as *mut i32;
    let r2 = &array[1] as *const i32;
    unsafe {
        println!("r1 is: {}", *r1);
        *r1 = 10;
        println!("r1 is: {}", *r1);
        println!("r2 is: {}", *r2);
    }
    println!("array is: {array:?}");
}
```

Miri looks happy about it.

2023-03-07 14:47 UTC, gendx commented
Bonus code to modify if you want to get to Miri:

```rust
fn main() {
    let mut array = [5, 6];
    let r1 = &mut array[0] as *mut i32;
    let r2 = &array[1] as *const i32;
    unsafe {
        println!("r1 is: {}", *r1);
        *r1 = 10;
        println!("r1 is: {}", *r1);
        // Undefined behavior because this breaks the aliasing rules, as
        // r1.offset(1) and r2 are aliasing the same memory.
        //*r1.offset(1) = 20;
        println!("r2 is: {}", *r2);
    }
    println!("array is: {array:?}");
}
```

2023-03-08 17:31 UTC, qwandor commented
How about #486 instead?

2023-03-19 18:26 UTC, closed without merging