Generalize the day-4 afternoon
google/comprehensive-rust pull request #487
Opened 2023-03-08 23:23 UTC by djmitche

This is in preparation for adding more options for this portion of the course, and reflects an existing practice of substituting other materials for this last half-day.

See #181 for the first of those new topics.

2023-03-09 10:26 UTC, mgeisler commented on src/running-the-course/day-4.md
> +If you don't skip the Android specific parts on Day 4, you will need an [AOSP
```suggestion
You will need an [AOSP
```

2023-03-09 10:27 UTC, mgeisler commented on src/running-the-course.md
> +1. Prepare anything you need to hand for the afternoon of day 4.
> need to hand

sounds odd to me?

2023-03-09 10:27 UTC, mgeisler approved these changes
Nice!

2023-03-09 10:45 UTC, mgeisler requested changes
I just remembered that we have a simple way to avoid broken links via the `book.toml` file.

2023-03-09 10:45 UTC, mgeisler commented on src/SUMMARY.md
> +- [Exercises](exercises/day-4/android.md)
Please update [`book.toml`](https://github.com/google/comprehensive-rust/blob/main/book.toml#L44) accordingly to avoid a broken link.

2023-03-09 12:05 UTC, rbehjati approved these changes
Thanks for putting this together. I think it would be nice to be more specific about the options are for Day 4 afternoon.

2023-03-09 15:01 UTC, djmitche commented on src/running-the-course.md
> +1. Prepare anything you need to hand for the afternoon of day 4.
That might be a regional thing..

2023-03-09 15:05 UTC, djmitche commented on src/running-the-course/course-structure.md
> +* Day 4: Concurrency in Rust and a topic chosen at your discretion.
I like "seeing Rust in action"!

2023-03-09 15:13 UTC, djmitche commented on src/running-the-course.md
> +To run the course, you need to:
They're things to do in advance, but you're right - the distinction isn't really important.

2023-03-10 10:17 UTC, mgeisler approved these changes

2023-03-10 10:21 UTC, mgeisler commented
Looks nice. Longer term, I'm envisioning us having a structure with

* Days 1-3: core Rust which everybody should know
* A whole suite of optional days:
  * Rust in Android
  * Interoperability with other languages
  * Unsafe in detail
  * Macro development
  * Bare-metal Rust
  * Async
  * Webassembly

The topics for extra days won't be coupled directly with core Rust part, so it won't really be "Day 4: Android" any longer. Instead, I'm imagining the topics will be taught on a more ad-hoc basis based on availability of instructors.

2023-03-10 14:07 UTC, merged