Translated `Chapter 1` to German
google/comprehensive-rust pull request #577
Opened 2023-04-21 21:02 UTC by Throvn

I'm sorry for the confusion but it is best to revert back to the rust book syntax when translating important rust vocabulary ("German (english)" instead of "English (german)").
The reason behind that is that otherwise you would have to conjugate the english word which would turn it into "Denglish". 

Also the reading flow is way better:
- "Für den Async-spezifischen Teil an Tag 4 benötigst du eine frisch erstellte Kiste (crate)." vs.
- "Für den Async-spezifischen Teil an Tag 4 benötigst du eine frisch erstellte Crate (Kiste)."

2023-04-24 06:11 UTC, ronaldfw requested changes
LGTM, only some minor nits

2023-04-24 06:11 UTC, ronaldfw commented on po/de.po
> +"1. Setze dich mit dem Kursmaterial auseinander. Wir haben Sprechernotizen hinzugefügt um "
```suggestion
"1. Setze dich mit dem Kursmaterial auseinander. Wir haben Sprechernotizen hinzugefügt, um "
```

2023-04-24 06:11 UTC, ronaldfw commented on po/de.po
> +"Teilnehmeranzahl von 15 bis 20 Leuten. Das schafft ein gutes Klima um Fragen zu stellen und es ist "
```suggestion
"Teilnehmeranzahl von 15 bis 20 Leuten. Das schafft ein gutes Klima, um Fragen zu stellen, und es ist "
```

2023-04-24 06:11 UTC, ronaldfw commented on po/de.po
> +"1. Sei schon etwas vor dem ersten Termin da um alles vorzubereiten. Wir schlagen vor, dass du "
```suggestion
"1. Sei schon etwas vor dem ersten Termin da, um alles vorzubereiten. Wir schlagen vor, dass du "
```

2023-04-24 06:11 UTC, ronaldfw commented on po/de.po
> +"Könntest du zeigen wo man die relevante Information in der Standardbibliothek findet.\n"
```suggestion
"könntest du zeigen wo man die relevante Information in der Standardbibliothek findet.\n"
```

2023-04-24 06:11 UTC, ronaldfw commented on po/de.po
> +"Dieser Abschnitt des Kurses ermöglicht es Teilnehmern Rust in einer Codebasis zu sehen die "
```suggestion
"Dieser Abschnitt des Kurses ermöglicht es Teilnehmern Rust in einer Codebasis zu sehen die sie"
```

2023-04-24 06:11 UTC, ronaldfw commented on po/de.po
> +"die Beispiele in `src/main.rs` eingefügt werden um mit ihnen zu experimentieren."
```suggestion
"die Beispiele in `src/main.rs` eingefügt werden, um mit ihnen zu experimentieren."
```

2023-04-24 06:11 UTC, ronaldfw commented on po/de.po
> +msgstr "Benutze die Sprachenauswahl oben rechts um die Sprache zu wechseln."
```suggestion
msgstr "Benutze die Sprachenauswahl oben rechts, um die Sprache zu wechseln."
```

2023-05-05 08:07 UTC, mgeisler approved these changes
Thanks @Throvn for applying the changes requested by @ronaldfw. Let's merge this now so that it becomes easier to iterate on.

2023-05-05 08:08 UTC, merged