Translate testing.md to zh-TW
google/comprehensive-rust pull request #774
Opened 2023-06-05 17:10 UTC by johnathan79717

I know that "supported" is directly translated to "支援", but I somehow feel awkward to use that in a sentence.  I welcome ideas and suggestions.

2023-06-05 17:51 UTC, victorhsieh requested changes

2023-06-05 17:51 UTC, victorhsieh commented on po/zh-TW.po
> +msgstr "Rust 和 Cargo 帶有一個簡單的單元測試 (unit test) 框架："
帶有 -> 提供了?
：-> ": " (半型加空白)

2023-06-05 17:51 UTC, victorhsieh commented on po/zh-TW.po
> +"* 單元測試在你的程式碼的任何地方都可添加。\n"
單元測試在你的程式碼的任何地方都可添加 -> 在你的程式碼的任何地方都可添加單元測試?

2023-06-05 17:51 UTC, victorhsieh commented on po/zh-TW.po
> +"* 集成測試 (integration test) 則在 `tests/` 資料夾下可添加。"
則在 `tests/` 資料夾下可添加 -> 則可以放置在 `tests/` 資料夾下

2023-06-06 05:53 UTC, mingyc commented on po/zh-TW.po
> +"* 集成測試 (integration test) 則在 `tests/` 資料夾下可添加。"
> 集成測試 (integration test)

I feel that `集成測試` is not a native term in zh-TW (correct me if I am wrong).

According to [wiki TW](https://zh.wikipedia.org/wiki/%E9%9B%86%E6%88%90%E6%B5%8B%E8%AF%95), it should be `整合測試`.

2023-06-06 10:32 UTC, johnathan79717 commented
Thanks for the suggestions.  I updated the commit!

2023-06-07 00:51 UTC, victorhsieh approved these changes

2023-06-09 09:07 UTC, merged