zh-TW: translation for src/control-flow/blocks.md
google/comprehensive-rust pull request #782
Opened 2023-06-07 10:43 UTC by kuanhungchen

Part of #684.

2023-06-07 14:06 UTC, victorhsieh requested changes

2023-06-08 11:27 UTC, kuanhungchen commented on po/zh-TW.po
> +"達式："
Not sure if you're referring to colons. According to localization style guide, colons should be 全形 in documentation. (Correct me if I'm wrong, thx)

2023-06-08 11:30 UTC, kuanhungchen commented on po/zh-TW.po
> +"* 你可以藉由改變區塊中的最後一行來改變區塊的數值。舉例來說，新增 / 刪除一個分"
Updated.

2023-06-08 13:39 UTC, victorhsieh commented on po/zh-TW.po
> +"達式："
You're right about the colon.  Thanks for correcting me :)

2023-06-08 13:39 UTC, victorhsieh approved these changes

2023-06-08 22:04 UTC, merged