zh-CN: Add translation for pattern-matching.md
google/comprehensive-rust pull request #821
Opened 2023-06-15 04:35 UTC by anlunx

For #324

2023-06-15 13:09 UTC, HAMMERABA approved these changes

2023-06-16 01:07 UTC, wnghl requested changes

2023-06-16 01:07 UTC, wnghl commented on po/zh-CN.po
> +"  *`1.。=5` 代表了一个闭区间范围\n"
```suggestion
"  *`1..=5` 代表了一个闭区间范围\n"
```

2023-06-20 00:54 UTC, wnghl approved these changes

2023-06-20 00:54 UTC, merged