zh-TW: Translate android/build-rules.md
google/comprehensive-rust pull request #824
Opened 2023-06-15 21:08 UTC by enshuoh

Part of https://github.com/google/comprehensive-rust/issues/684.

2023-06-21 07:40 UTC, mingyc requested changes

2023-06-21 07:40 UTC, mingyc commented on po/zh-TW.po
> +msgstr "Android 建構系統 (Soong) 透過以下模組支援 Rust："
How about adding `的`: `Android 的建構系統`

2023-06-21 07:40 UTC, mingyc commented on po/zh-TW.po
> +"| `rust_fuzz`       | 利用 `libfuzzer` 生成一個Rust模糊測試的二進位 "
Add space in between Rust: `生成一個 Rust 的模糊測試的二進位執行檔`

2023-06-21 07:40 UTC, mingyc commented on po/zh-TW.po
> +"代碼及函式庫 。                            |\n"
> Generates source and produces a Rust library that provides an interface for a particular protobuf. 
> 對指定的protobuf，生成其定義界面的 Rust 代碼及函式庫 。           

`生成對應 protobuf 介面的 Rust 原始碼及函式庫 。`

2023-06-21 07:40 UTC, mingyc commented on po/zh-TW.po
> +"代碼及函式庫。                             |"
`代碼` -> `原始碼`

2023-06-21 08:29 UTC, mgeisler commented on po/zh-TW.po
> +"代碼及函式庫。                             |"
I forget if I already showed you the suggestion feature (left-most button in the toolbar above):

```suggestion
"原始碼及函式庫。                             |"
```

That allows the PR author (or yourself!) to incorporate the change with a single click.

2023-07-21 18:16 UTC, victorhsieh requested changes

2023-07-27 09:45 UTC, mgeisler commented
Hi @victorhsieh, feel free to use the suggestion feature here to fix up the things you feel confident about. You can then apply the fixes directly and merge the PR. That often saves a lot of round-trips for the translations.

2023-07-27 17:36 UTC, victorhsieh commented on po/zh-TW.po
> +"| `rust_binary`     | 生成一個 Rust 二進位執行檔。"
```suggestion
"| `rust_binary`     | 生成一個 Rust 執行檔。"
```

2023-07-27 17:36 UTC, victorhsieh commented on po/zh-TW.po
> +"| `rust_ffi`        | 生成一個可被 `cc` 模組使用的  Rust C 函式庫，及其對應的"
```suggestion
"| `rust_ffi`        | 生成一個可被 `cc` 模組使用的 Rust C 函式庫，及其對應的"
```

2023-07-27 17:36 UTC, victorhsieh commented on po/zh-TW.po
> +"| `rust_fuzz`       | 利用 `libfuzzer` 生成一個 Rust 模糊測試的二進位 "
```suggestion
"| `rust_fuzz`       | 生成一個使用 libfuzzer 的 Rust 模糊測試"
```

2023-08-04 22:06 UTC, hueich commented on po/zh-TW.po
> +"| `rust_fuzz`       | 利用 `libfuzzer` 生成一個 Rust 模糊測試的二進位 "
Remember to add the backticks.

2023-08-04 22:07 UTC, hueich reviewed
Agree with Victor's suggestions.

2023-08-13 14:41 UTC, mgeisler commented on po/zh-TW.po
> +"| `rust_fuzz`       | 利用 `libfuzzer` 生成一個 Rust 模糊測試的二進位 "
There, I added the backticks :smile: 

```suggestion
"| `rust_fuzz`       | 生成一個使用 `libfuzzer` 的 Rust 模糊測試"
```

2023-08-13 14:43 UTC, mgeisler commented
Hey all! Let's get this merged so you can start seeing it in context of the rest of the book. That would make it easier to apply any small corrections needed (and it would make it easier for you to [refresh the translation](https://github.com/google/comprehensive-rust/blob/main/TRANSLATIONS.md#refreshing-an-existing-translation)).

2023-08-13 14:43 UTC, mgeisler commented
@victorhsieh and @mingyc, you asked for changes in your review — please take another quick look.

2023-08-14 16:22 UTC, victorhsieh approved these changes
I had one open, nit-picking comment, but am ok to merge without it.

2023-08-14 17:55 UTC, mgeisler commented
> I had one open, nit-picking comment, but am ok to merge without it.

Thanks! I just converted your comment straight into an issue: #1080. Then it should be possible to revisit after merging this and after upgrading mdbook-i18n-helpers.

2023-08-14 17:55 UTC, mgeisler commented on po/zh-TW.po
> +"擴充。                                      |\n"
Moved to #1080.

2023-08-14 18:02 UTC, mgeisler commented
> Sorry for dropping the ball. Lost my attention to the thread waiting for review.

All good! :smile: A lot of things have been in flight here so it's hard to stay on top of it all.

> It seems Victor hasn't gotten the CLA, blocking the merge.

Yeah, though Victor is a Googler so the problem is the use of a private email address. I'll override it and then we should be able to merge.

2023-08-14 18:02 UTC, merged