Update ru.po
google/comprehensive-rust pull request #832
Opened 2023-06-19 15:50 UTC by git-user-cpp

Added Russian translation

2023-06-19 22:59 UTC, zvonden requested changes
Кажется, что имеет смысл переводить оглавление только вместе с переводом самих глав, тогда смысл названия и терминология будут точны и понятны, а так - гадаем в половине случаев, что имелось в виду.

2023-06-19 22:59 UTC, zvonden commented on po/ru.po
> +msgstr "Привет мир!"
add comma please

2023-06-19 22:59 UTC, zvonden commented on po/ru.po
> +msgstr "Маленький пример"
короткий

2023-06-19 22:59 UTC, zvonden commented on po/ru.po
> +msgstr "Гарантия времени компиляции"
гарантии

2023-06-19 22:59 UTC, zvonden commented on po/ru.po
> +msgstr "Массивы и цикл for"
циклы

2023-06-19 22:59 UTC, zvonden commented on po/ru.po
> +msgstr "День 1: Полдень"
возможно "вечер"

2023-06-19 22:59 UTC, zvonden commented on po/ru.po
> +msgstr "Область видимости и затенение"
Области?

2023-06-19 22:59 UTC, zvonden commented on po/ru.po
> +msgstr "Стек против кучи"
Стек и куча

2023-06-19 22:59 UTC, zvonden commented on po/ru.po
> +msgstr "Память стека"
скорее "стековая память" - смотря что там за контент

2023-06-19 22:59 UTC, zvonden commented on po/ru.po
> +msgstr "Итераторы и право собственности"
Чуть выше этот же термин был переведен как Владение.

2023-06-19 22:59 UTC, zvonden commented on po/ru.po
> +msgstr "Сокращенный синтаксис поля"
не уверен, что так - надо бы на смысл посмотреть

2023-06-19 22:59 UTC, zvonden commented on po/ru.po
> +msgstr "Перечисляемый тип"
перечисле́ние? https://ru.wikipedia.org/wiki/%D0%9F%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%81%D0%BB%D1%8F%D0%B5%D0%BC%D1%8B%D0%B9_%D1%82%D0%B8%D0%BF

2023-06-19 22:59 UTC, zvonden commented on po/ru.po
> +msgstr "Вариант полезной нагрузки"
или наоборот вариабельная нагрузка?

2023-06-19 22:59 UTC, zvonden commented on po/ru.po
> +msgstr "Размеры перечисления"
перечислений?

2023-06-19 22:59 UTC, zvonden commented on po/ru.po
> +msgstr "Приемник метода"
получатель?

2023-06-19 22:59 UTC, zvonden commented on po/ru.po
> +msgstr "Разрушение перечислений"
деструктурирование?

2023-06-19 22:59 UTC, zvonden commented on po/ru.po
> +msgstr "Разрушение структур"
деструктурирование?

2023-06-19 22:59 UTC, zvonden commented on po/ru.po
> +msgstr "Разрушение массивов"
деструктурирование?

2023-06-20 05:36 UTC, closed without merging

2023-06-20 07:55 UTC, mgeisler commented on po/ru.po
> +msgstr "Массивы и цикл for"
Just a small comment: you can save people time by using the suggestion feature in GitHub:

```suggestion
msgstr "Массивы и циклы for"
```

(I'm guessing this is the correction you're suggesting)