zh-TW: translate ownership
google/comprehensive-rust pull request #860
Opened 2023-06-23 13:27 UTC by mgeisler

2023-06-23 14:14 UTC, johnathan79717 requested changes

2023-06-23 14:14 UTC, johnathan79717 commented on po/zh-TW.po
> +msgstr "您可以不必在呼叫函式時轉移擁有權，而是讓函式「借用」__值："
```suggestion
msgstr "您可以不必在呼叫函式時轉移擁有權，而是讓函式「借用」值："
```

2023-06-23 14:14 UTC, johnathan79717 commented on po/zh-TW.po
> +"* 示範因為編譯器可刪除複製作業，所以 `add` 回傳作業的成本較低。變更上述程式碼"
```suggestion
"* 示範因為編譯器可刪除複製操作，所以 `add` 回傳的成本較低。變更上述程式碼"
```

2023-06-23 14:47 UTC, HAMMERABA approved these changes

2023-06-23 14:47 UTC, HAMMERABA approved these changes

2023-06-23 14:49 UTC, HAMMERABA commented
Hi,
So your not Inditted,  I need some of your data to go online.
+233204349899

On Fri, Jun 23, 2023, 14:14 Jonathan Hao ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In po/zh-TW.po
> <https://github.com/google/comprehensive-rust/pull/860#discussion_r1239838609>
> :
>
> > @@ -3750,14 +3750,14 @@ msgstr ""
>
>  #: src/ownership.md:1
>  msgid "# Ownership"
> -msgstr ""
> +msgstr "# 擁有權"
>
> Ownership was translated to "所有權" in
> https://rust-lang.tw/book-tw/ch04-00-understanding-ownership.html. Do we
> want to follow?
> ------------------------------
>
> In po/zh-TW.po
> <https://github.com/google/comprehensive-rust/pull/860#discussion_r1239842362>
> :
>
> >
>  #: src/ownership.md:3
>  msgid ""
>  "All variable bindings have a _scope_ where they are valid and it is an error "
>  "to\n"
>  "use a variable outside its scope:"
> -msgstr ""
> +msgstr "所有變數繫結都會在特定「範圍」__內有效，在範圍外使用變數會是錯誤："
>
> ⬇️ Suggested change
>
> -msgstr "所有變數繫結都會在特定「範圍」__內有效，在範圍外使用變數會是錯誤："
> +msgstr "所有變數繫結都會在特定「範圍」內有效，在範圍外使用變數會是錯誤："
>
> The underscores were supposed to make "scope" italic, but I don't think we
> need it since we already have 「」
> ------------------------------
>
> In po/zh-TW.po
> <https://github.com/google/comprehensive-rust/pull/860#discussion_r1239843555>
> :
>
> >
>  #: src/ownership.md:18
>  msgid ""
>  "* At the end of the scope, the variable is _dropped_ and the data is freed.\n"
>  "* A destructor can run here to free up resources.\n"
>  "* We say that the variable _owns_ the value."
>  msgstr ""
> +"* 範圍結束時，變數會遭到「捨棄」__，資料也會釋放。\n"
> +"* 解構函式可在這時執行，用來釋放資源。\n"
> +"* 我們會說變數「擁有」__值。"
>
> ⬇️ Suggested change
>
> -"* 我們會說變數「擁有」__值。"
> +"* 我們會說變數「擁有」值。"
>
> Same
> ------------------------------
>
> In po/zh-TW.po
> <https://github.com/google/comprehensive-rust/pull/860#discussion_r1239848030>
> :
>
> >
>  #: src/ownership/move-semantics.md:3
>  msgid "An assignment will transfer ownership between variables:"
> -msgstr ""
> +msgstr "指派作業會在變數之間轉移擁有權："
>
> ⬇️ Suggested change
>
> -msgstr "指派作業會在變數之間轉移擁有權："
> +msgstr "指派會在變數之間轉移擁有權："
>
> ------------------------------
>
> In po/zh-TW.po
> <https://github.com/google/comprehensive-rust/pull/860#discussion_r1239848642>
> :
>
> > @@ -3809,6 +3831,11 @@ msgid ""
>  "* When `s2` goes out of scope, the string data is freed.\n"
>  "* There is always _exactly_ one variable binding which owns a value."
>  msgstr ""
> +"* 將 `s1` 指派給 `s2` 會轉移擁有權。\n"
> +"* 資料已從 `s1`「移出」__，`s1` 無法再供存取。\n"
>
> ⬇️ Suggested change
>
> -"* 資料已從 `s1`「移出」__，`s1` 無法再供存取。\n"
> +"* 資料已從 `s1`「移出」，`s1` 無法再供存取。\n"
>
> ------------------------------
>
> In po/zh-TW.po
> <https://github.com/google/comprehensive-rust/pull/860#discussion_r1239851427>
> :
>
> > @@ -3809,6 +3831,11 @@ msgid ""
>  "* When `s2` goes out of scope, the string data is freed.\n"
>  "* There is always _exactly_ one variable binding which owns a value."
>  msgstr ""
> +"* 將 `s1` 指派給 `s2` 會轉移擁有權。\n"
> +"* 資料已從 `s1`「移出」__，`s1` 無法再供存取。\n"
> +"* 當 `s1` 超出範圍時，系統不會執行任何動作，因為 `s1` 沒有擁有權。\n"
> +"* 當 `s2` 超出範圍時，系統會釋放字串資料。\n"
> +"* 一律「只有」__一個變數繫結會擁有值。"
>
> ⬇️ Suggested change
>
> -"* 一律「只有」__一個變數繫結會擁有值。"
> +"* 一律「只有」一個變數綁定會擁有值。"
>
> 綁定 is according to
> https://zh.wikipedia.org/wiki/%E5%90%8D%E5%AD%97%E7%BB%91%E5%AE%9A
> ------------------------------
>
> In po/zh-TW.po
> <https://github.com/google/comprehensive-rust/pull/860#discussion_r1239856361>
> :
>
> >
>  #: src/ownership/double-free-modern-cpp.md:1
>  msgid "# Double Frees in Modern C++"
> -msgstr ""
> +msgstr "# 現代 C++ 中的重複釋放"
>
> ⬇️ Suggested change
>
> -msgstr "# 現代 C++ 中的重複釋放"
> +msgstr "# 現代 C++ 中的雙重釋放"
>
> ------------------------------
>
> In po/zh-TW.po
> <https://github.com/google/comprehensive-rust/pull/860#discussion_r1239868649>
> :
>
> >
>  #: src/ownership/borrowing.md:3
>  msgid ""
>  "Instead of transferring ownership when calling a function, you can let a\n"
>  "function _borrow_ the value:"
> -msgstr ""
> +msgstr "您可以不必在呼叫函式時轉移擁有權，而是讓函式「借用」__值："
>
> ⬇️ Suggested change
>
> -msgstr "您可以不必在呼叫函式時轉移擁有權，而是讓函式「借用」__值："
> +msgstr "您可以不必在呼叫函式時轉移擁有權，而是讓函式「借用」值："
>
> ------------------------------
>
> In po/zh-TW.po
> <https://github.com/google/comprehensive-rust/pull/860#discussion_r1239868885>
> :
>
> >
>  #: src/ownership/borrowing.md:22
>  msgid ""
>  "* The `add` function _borrows_ two points and returns a new point.\n"
>  "* The caller retains ownership of the inputs."
>  msgstr ""
> +"* `add` 函式會「借用」__兩個點，並傳回新的點。\n"
>
> ⬇️ Suggested change
>
> -"* `add` 函式會「借用」__兩個點，並傳回新的點。\n"
> +"* `add` 函式會「借用」兩個點，並傳回新的點。\n"
>
> ------------------------------
>
> In po/zh-TW.po
> <https://github.com/google/comprehensive-rust/pull/860#discussion_r1239870353>
> :
>
> > @@ -4157,20 +4336,48 @@ msgid ""
>  "all. If RVO did not happen, Rust will always performs a simple and efficient "
>  "`memcpy` copy."
>  msgstr ""
> +"* 示範因為編譯器可刪除複製作業，所以 `add` 回傳作業的成本較低。變更上述程式碼"
>
> ⬇️ Suggested change
>
> -"* 示範因為編譯器可刪除複製作業，所以 `add` 回傳作業的成本較低。變更上述程式碼"
> +"* 示範因為編譯器可刪除複製操作，所以 `add` 回傳的成本較低。變更上述程式碼"
>
> ------------------------------
>
> In po/zh-TW.po
> <https://github.com/google/comprehensive-rust/pull/860#discussion_r1239871369>
> :
>
> >
>  #: src/ownership/shared-unique-borrows.md:5
>  msgid ""
>  "* You can have one or more `&T` values at any given time, _or_\n"
>  "* You can have exactly one `&mut T` value."
>  msgstr ""
> +"* 隨時擁有一或多個 `&T` 值，「或是」__\n"
>
> ⬇️ Suggested change
>
> -"* 隨時擁有一或多個 `&T` 值，「或是」__\n"
> +"* 隨時擁有一或多個 `&T` 值，「或是」\n"
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/google/comprehensive-rust/pull/860#pullrequestreview-1495179418>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BAKXIEVJCFN6T2KWIFPLSHLXMWQFDANCNFSM6AAAAAAZRSIKHM>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2023-06-26 11:59 UTC, mgeisler commented on po/zh-TW.po
> +msgstr "# 擁有權"
I generally suggest using the same terminology as the Rust book! So if you're happy with the terminology from there, then we should use it.

2023-06-27 13:27 UTC, johnathan79717 requested changes
Please replace 擁有權 with 所有權.  Thanks.

2023-06-27 16:17 UTC, mgeisler commented
> Please replace 擁有權 with 所有權. Thanks.

Sure, I did a search and replace on the whole file.

2023-06-28 07:17 UTC, johnathan79717 approved these changes

2023-06-28 07:18 UTC, johnathan79717 commented
Thanks.  There were a few "__" left.  I pushed a commit to edit them out.

2023-06-28 07:20 UTC, merged