zh-TW: translate cargo
google/comprehensive-rust pull request #871
Opened 2023-06-23 13:28 UTC by mgeisler

2023-06-23 13:42 UTC, johnathan79717 requested changes

2023-06-23 13:42 UTC, johnathan79717 commented on po/zh-TW.po
> +"您可以在 Debian/Ubuntu 上使用下列程式碼，安裝 Cargo、Rust 來源和 [Rust 格式設"
```suggestion
"您可以在 Debian/Ubuntu 上使用下列程式碼，安裝 Cargo、Rust 原始碼和 [Rust 格式設"
```

2023-06-23 13:42 UTC, johnathan79717 commented on po/zh-TW.po
> +"crits.io> 上代管的依附元件，且會在建構您的專案時，將這些依附元件傳送至 "
```suggestion
"crates.io> 上代管的依附元件，且會在建構您的專案時，將這些依附元件傳送至 "
```

2023-06-23 13:42 UTC, johnathan79717 commented on po/zh-TW.po
> +"完成上述步驟後，請按照下列步驟操作，在本訓練課程的任一範例中建立 Rust 二進位"
We may want to unify how "build" is translated.  In earlier of this file, it was translated to "建構".

2023-06-28 07:22 UTC, johnathan79717 commented on po/zh-TW.po
> +"完成上述步驟後，請按照下列步驟操作，在本訓練課程的任一範例中建立 Rust 二進位"
Actually only replace only when it's translated from "build", not from "create".

2023-06-28 07:24 UTC, johnathan79717 approved these changes

2023-06-28 07:25 UTC, johnathan79717 commented on po/zh-TW.po
> +"完成上述步驟後，請按照下列步驟操作，在本訓練課程的任一範例中建立 Rust 二進位"
I pushed a commit to fix this.

2023-06-28 07:56 UTC, mgeisler commented on po/zh-TW.po
> +"完成上述步驟後，請按照下列步驟操作，在本訓練課程的任一範例中建立 Rust 二進位"
Thanks! I cannot read Chinese, so good that you caught this :sweat_smile:

2023-06-28 07:56 UTC, merged