ru: Day 1: Morning translation
google/comprehensive-rust pull request #903
Opened 2023-07-04 21:21 UTC by baltuky

Russian translation for chapter `Day 1: Morning`

2023-07-05 21:20 UTC, zvonden requested changes

2023-07-05 21:20 UTC, zvonden commented on po/ru.po
> +msgstr "Это первый день курса. Сегодня мы рассмотрим много интересного:"
в оригинале имелось в виду, что базовые вещи будут покрыты, а не интересные

2023-07-05 21:20 UTC, zvonden commented on po/ru.po
> +"* Базовый синтаксис Rust: переменные, примитивные и составные типы, перечисления,\n"
```suggestion
"* Базовый синтаксис Rust: переменные, скалярные и составные типы, перечисления,\n"
```

2023-07-05 21:20 UTC, zvonden commented on po/ru.po
> +"* Они могут задавать вопросы по мере их появления, не откладывайте их до конца.\n"
```suggestion
"* Они могут задавать вопросы по мере их появления, не откладывая их до конца.\n"
```

2023-07-05 21:20 UTC, zvonden commented on po/ru.po
> +"например, поддерживать обсуждения, связанные с тем, как Rust делает вещи по сравнению с каким--либо другим языком. \n"
```suggestion
"например, поддерживать обсуждения, связанные с тем, как в Rust делается что-либо в сравнении с каким--либо другим языком. \n"
```

2023-07-05 21:20 UTC, zvonden commented on po/ru.po
> +"* Вопросы, скорее всего, будут означать, что речь идет о вещах, опережающих показ слайдов.\n"
```suggestion
"* Часто вопросы будут приводить к обсуждениям, опережающим порядок показа слайдов.\n"
```

2023-07-05 21:20 UTC, zvonden commented on po/ru.po
> +"важной особенностью и мы должны показать это студентам с самого начала."
```suggestion
"иметь возможность говорить о знаменитом анализаторе заимствований. То, как Rust работает с памятью ---\n"
"важная особенность языка и мы должны показать её студентам с самого начала."
```

2023-07-05 21:20 UTC, zvonden commented on po/ru.po
> +"Пожалуйста, не забудьте добавить перерывы, мы рекомендуем делать перерыв каждый час!"
```suggestion
"Пожалуйста, не забудьте добавить перерывы. Мы рекомендуем делать перерыв каждый час!"
```

2023-07-05 21:31 UTC, baltuky commented on po/ru.po
> +msgstr "Примитивные типы"
👌

2023-07-05 21:33 UTC, baltuky commented on po/ru.po
> +msgstr "Это первый день курса. Сегодня мы рассмотрим много интересного:"
Changed it to be `Сегодня мы пройдемся по многим темам:`. Hope that looks better

2023-07-07 13:35 UTC, DarthGandalf commented on po/ru.po
> +msgstr "Это первый день курса. Сегодня мы рассмотрим много интересного:"
Может, пройдёмся тогда, через ё?

2023-07-07 13:50 UTC, baltuky commented on po/ru.po
> +msgstr "Это первый день курса. Сегодня мы рассмотрим много интересного:"
Done! 👍

2023-07-07 13:50 UTC, DarthGandalf approved these changes

2023-07-07 13:50 UTC, DarthGandalf commented on po/ru.po
> +msgstr "Давайте перейдем к самой простой из возможных программ на Rust, классической программе Привет, мир!"
перейдём

2023-07-07 13:50 UTC, DarthGandalf commented on po/ru.po
> +"На этом слайде мы пытаемся помочь студентам ознакомиться с кодом на Rust.\n"
четырёх

2023-07-07 13:50 UTC, DarthGandalf commented on po/ru.po
> +"* “Гигиеничность” макросов означает, что они случайно не захватывают идентификаторы из области, в которой они используются. Макросы в Rust на самом деле гигиеничны лишь [частично](https://veykril.gi
Мне кажется, в русском кавычки другие - «» либо „“ если вложенные

2023-07-07 13:50 UTC, DarthGandalf commented on po/ru.po
> +"* Нет инвалидации итератора."
итераторов?

2023-07-07 13:50 UTC, DarthGandalf commented on po/ru.po
> +"  поэтому она должна быть чрезвычайно стабильной. В приведенных выше примерах сообщество Rust все еще работает над\n"
приведённых, всё ещё

2023-07-07 13:50 UTC, DarthGandalf commented on po/ru.po
> +msgstr "# Висящие ссылки"
Висячие всё-таки, а не висящие

https://ru.wikipedia.org/wiki/%D0%92%D0%B8%D1%81%D1%8F%D1%87%D0%B8%D0%B9_%D1%83%D0%BA%D0%B0%D0%B7%D0%B0%D1%82%D0%B5%D0%BB%D1%8C

2023-07-07 17:48 UTC, baltuky commented on po/ru.po
> +msgstr "Давайте перейдем к самой простой из возможных программ на Rust, классической программе Привет, мир!"
Fixed!

2023-07-07 17:48 UTC, baltuky commented on po/ru.po
> +"На этом слайде мы пытаемся помочь студентам ознакомиться с кодом на Rust.\n"
Fixed!

2023-07-07 17:48 UTC, baltuky commented on po/ru.po
> +"* “Гигиеничность” макросов означает, что они случайно не захватывают идентификаторы из области, в которой они используются. Макросы в Rust на самом деле гигиеничны лишь [частично](https://veykril.gi
Fixed!

2023-07-07 17:48 UTC, baltuky commented on po/ru.po
> +"* Нет инвалидации итератора."
Fixed!

2023-07-07 17:48 UTC, baltuky commented on po/ru.po
> +"  поэтому она должна быть чрезвычайно стабильной. В приведенных выше примерах сообщество Rust все еще работает над\n"
Fixed!

2023-07-07 17:49 UTC, baltuky commented on po/ru.po
> +msgstr "# Висящие ссылки"
Fixed!

2023-07-26 08:36 UTC, mgeisler commented
I think the suggestions from @zvonden have all been applied, so we can merge this now?

2023-07-26 09:16 UTC, dyeroshenko approved these changes
LGTM

2023-07-26 20:21 UTC, merged

2023-07-26 20:22 UTC, baltuky commented
> I think the suggestions from @zvonden have all been applied, so we can merge this now?

I will merge it. Anyway, we can polish it even more later if we need to.

2023-07-27 06:40 UTC, mgeisler commented
> > I think the suggestions from @zvonden have all been applied, so we can merge this now?
> 
> I will merge it. Anyway, we can polish it even more later if we need to.

Thanks!