zh-TW: translate std
google/comprehensive-rust pull request #964
Opened 2023-07-13 13:01 UTC by mgeisler

Part of ##684.

2023-07-26 08:32 UTC, mgeisler commented
Hey all, please take a look and leave suggestions if there is something here I should fix.

2023-07-26 15:22 UTC, johnathan79717 requested changes

2023-07-26 15:22 UTC, johnathan79717 commented on po/zh-TW.po
> +"資料儲存在 `Box` 的堆積上，這樣系統就只會移動指標。"
```suggestion
"* `Box` 就像是 C++ 中的 `std::unique_ptr`，兩者的差別在於 `Box` 不會是空值。\n"
"* 上面的範例使用 `Deref`，因此 `println!` 陳述式甚至可以省略 `*`。\n"
"* 在以下情況下，您可以使用 `Box`：\n"
"   * 編譯時遇到不知道大小為何的類型，但 Rust 編譯器需要知道確切大小。\n"
"   * 想要轉移大量資料的所有權。為避免在堆疊上複製大量資料，請改將"
"資料儲存在 `Box` 的堆積上，這樣系統就只會移動指標。"
```

2023-07-27 06:43 UTC, mgeisler commented on po/zh-TW.po
> +"指標。* [`Rc`](std/rc.md)：堆積配置資料的共用參考指標。"
> I notice that many newlines between list items have been removed in this PR.

Yeah, I think our tooling displays the text in a way that isn't useful to the translators. So they struggle to recreate the Markdown in the translation and result is what you see. I'll go over the other PRs and fix them.

2023-07-27 07:43 UTC, mgeisler commented on po/zh-TW.po
> +"指標。* [`Rc`](std/rc.md)：堆積配置資料的共用參考指標。"
#1036 will fix some more instances of this (hopefully all).

2023-07-27 09:35 UTC, johnathan79717 approved these changes

2023-07-27 09:35 UTC, johnathan79717 commented on po/zh-TW.po
> +msgstr "[`Box`][1] 是指向堆積上的資料的具有所有權的指標："
```suggestion
msgstr "[`Box`][1] 是具有所有權的指向堆積上的資料的指標："
```

2023-07-27 09:35 UTC, johnathan79717 commented on po/zh-TW.po
> +"憶體中的結構體固定大小，結構體看起來會像是無限大。\n"
```suggestion
"* 如果這裡未使用 `Box`，且我們要將 `List` 直接嵌入 `List`，編譯器就不會計算出固定的"
"結構體記憶體大小，結構體看起來會像是無限大。\n"
```

2023-07-27 09:47 UTC, merged